import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const w=require('./weekly-checkin-service');
test('partial first and final Intervention weeks use Monday-Friday boundaries',()=>assert.deepEqual(w.interventionWeeks('2026-09-16','2026-09-22'),[{week_start:'2026-09-14',week_end:'2026-09-18'},{week_start:'2026-09-21',week_end:'2026-09-25'}]));
test('Qualtrics URL contains exactly encoded server context and safely replaces configured query/hash',()=>{const token='opaque token/+',url=new URL(w.buildQualtricsUrl(token,'MR 001/+',3,'https://example.qualtrics.com/jfe/form/SV_test?old=value#fragment'));assert.deepEqual([...url.searchParams.keys()],['mr_weekly_token','participant_code','week_number']);assert.equal(url.searchParams.get('mr_weekly_token'),token);assert.equal(url.searchParams.get('participant_code'),'MR 001/+');assert.equal(url.searchParams.get('week_number'),'3');assert.doesNotMatch(url.href,/old=value|fragment/);assert.match(url.href,/opaque\+token%2F%2B/);assert.match(url.href,/MR\+001%2F%2B/);});
test('Qualtrics configuration fails closed',()=>{for(const value of [undefined,'not a URL','http://x.qualtrics.com/jfe/form/SV_x','https://user:pass@x.qualtrics.com/jfe/form/SV_x','https://example.com/jfe/form/SV_x','https://x.qualtrics.com/not-a-survey'])assert.equal(w.qualtricsConfiguration(value).configured,false,String(value));assert.equal(w.qualtricsConfiguration('https://granite.co1.qualtrics.com/jfe/form/SV_weekly').configured,true);});
test('generated context never includes identifying or personalization data',()=>{const url=w.buildQualtricsUrl('token','MR-998',2,'https://x.qualtrics.com/jfe/form/SV_weekly');for(const forbidden of ['teacher','student','target_behavior','replacement_behavior','target_routine','case_id','diagnosis','mission'])assert.doesNotMatch(url,new RegExp(forbidden,'i'));});
test('neutral unsent email template has no performance priming',()=>{const email=w.weeklyEmail({teacherFirstName:'Pat',checkinUrl:'https://q.example/token'});assert.equal(email.subject,'Quick Mission: Reinforceable weekly check-in');assert.match(email.text,/1–2 minutes/);assert.doesNotMatch(email.text,/score|adherence|missed mission|hint|fidelity|student outcome/i);});
test('intervention week ordinal includes a partial first week',()=>{const history=[{id:'1',phase:'intervention',effective_date:'2026-09-16',recorded_at:'2026-09-01'}];assert.deepEqual(w.interventionWeekContext(history,'2026-09-17'),{week_start:'2026-09-14',week_end:'2026-09-18',week_number:1});assert.equal(w.interventionWeekContext(history,'2026-09-23').week_number,2);});
test('weeks with no Granite study days do not consume an intervention ordinal',()=>{const weeks=w.eligibleInterventionWeeks('2026-12-14','2027-01-08');assert.deepEqual(weeks.map(x=>x.week_start),['2026-12-14','2027-01-04']);});
test('same-date corrections and a later phase bound intervention timing',()=>{const history=[{id:'1',phase:'intervention',effective_date:'2026-09-14',recorded_at:'2026-09-01'},{id:'2',phase:'baseline',effective_date:'2026-09-14',recorded_at:'2026-09-02'},{id:'3',phase:'intervention',effective_date:'2026-09-16',recorded_at:'2026-09-03'},{id:'4',phase:'withdrawal',effective_date:'2026-09-29',recorded_at:'2026-09-04'}];assert.deepEqual(w.resolvedInterventionPeriod(history,'2026-10-01'),{start:'2026-09-16',end:'2026-09-28'});});
