import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import { RESOURCE_SECTIONS, buildFullDraftPayload, buildFullDraftSnapshot, validateFullDraft, validateMissionStructure } from './game-draft-validator.mjs';
const require = createRequire(import.meta.url);
const { validateStructure } = require('../scripts/structural-content-validator.js');
const { validateResources } = require('../scripts/resource-content-validator.js');

function mission(id) {
  const steps = {};
  for (let n = 1; n <= 5; n++) steps[`s${n}`] = { text: `Fictional scene ${n}`, meta: {}, choices: Object.fromEntries([[10, 'A'], [5, 'B'], [0, 'C']].map(([score, key]) => [key, n < 5 ? { text: 'Action', consequence: 'Outcome', feedback: 'Feedback', score, next: `s${n + 1}`, meta: {} } : { text: 'Action', consequence: 'Outcome', feedback: 'Feedback', score, next: null, ending: score === 10 ? 'STRONG' : score === 5 ? 'MIXED' : 'FRAGILE', meta: {} }])) };
  return { id, start: 's1', expectedSteps: 5, steps, endings: { STRONG: { text: 'Strong' }, MIXED: { text: 'Mixed' }, FRAGILE: { text: 'Fragile' } } };
}
function resources() { return { schemaVersion: 1, sections: Object.fromEntries(Object.entries(RESOURCE_SECTIONS).map(([key, title]) => [key, { title, blocks: [{ type: 'paragraph', text: 'Use a calm, brief plan-aligned response.' }] }])) }; }
function workspace() { const missions = []; for (const [type, count] of [['daily', 10], ['wild', 5], ['crisis', 5]]) for (let slot = count; slot; slot--) missions.push({ mission_type: type, slot_number: slot, mission: mission(`${type}_${slot}`) }); return { case: { id: 'case', case_code: 'CASE-998', student_alias: 'River' }, has_crisis_plan: false, setup_draft: { setup: { schemaVersion: 1, bipBriefing: 'Use the approved plan before each fictional mission.', weeklyTeacherReport: { targetBehavior: 'Target response', replacementBehavior: 'Desired response', targetRoutine: 'Class routine' } } }, resource_draft: { resources: resources() }, fidelity_targets: [], missions }; }

test('snapshot and protected payload use latest saved rows, slot sorting, authoritative alias, and null version', () => { const value = workspace(), snapshot = buildFullDraftSnapshot(value), payload = buildFullDraftPayload(value); assert.deepEqual(snapshot.missions.daily.map(item => item.slotNumber), [1,2,3,4,5,6,7,8,9,10]); assert.equal(payload.resources.studentAlias, 'River'); assert.equal(value.resource_draft.resources.studentAlias, undefined); assert.equal(payload.daily_missions[0].id, 'daily_1'); assert.equal(payload.version, null); });
test('complete 10/5/5 saved draft is previewable with human-review warning', () => { const report = validateFullDraft(workspace()); assert.equal(report.blockingCount, 0); assert.equal(report.ready, true); assert(report.categories['PRIVACY & SAFETY'].warnings.length > 0); });
test('setup and specific mission slots are blocking completeness requirements', () => { const value = workspace(); value.setup_draft.setup.bipBriefing = ''; value.setup_draft.setup.weeklyTeacherReport.targetRoutine = ''; value.missions = value.missions.filter(row => !(row.mission_type === 'daily' && row.slot_number === 4)); const report = validateFullDraft(value); assert.equal(report.ready, false); const messages = Object.values(report.categories).flatMap(category => category.errors.map(item => item.message)); assert(messages.includes('Daily 4 — Not started.')); assert(messages.some(message => /BIP Briefing/.test(message))); assert(messages.some(message => /Target Routine/.test(message))); });
test('browser mission structure rules stay in parity with runtime validator', () => { const valid = { daily: [mission('one')], wildcard: [], crisis: [] }; assert.equal(validateMissionStructure(valid).valid, validateStructure(valid).valid); valid.daily[0].steps.s2.choices.A.next = 'missing'; assert.equal(validateMissionStructure(valid).valid, validateStructure(valid).valid); });
test('strict browser Resource Map behavior stays in parity and privacy/HTML severity differs correctly', () => { const value = workspace(); let report = validateFullDraft(value); assert.equal(report.categories['RESOURCE MAP'].errors.length, 0); assert.equal(validateResources({ ...resources(), studentAlias: 'River' }, { expectedAlias: 'River' }).valid, true); value.resource_draft.resources.sections.bip.blocks[0].text = 'Contact person@example.org'; report = validateFullDraft(value); assert.equal(report.ready, true); assert(report.categories['PRIVACY & SAFETY'].warnings.some(item => /email/.test(item.message))); value.resource_draft.resources.sections.bip.blocks[0].text = '<script>bad()</script>'; assert.equal(validateFullDraft(value).ready, false); });
test('fidelity manifest and no-plan crisis safeguards block unsupported linkage but not Crisis mission type', () => { const value = workspace(); value.fidelity_targets = [{ target_key: 'proactive_01', domain: 'proactive' }]; let report = validateFullDraft(value); assert.equal(report.ready, true); value.missions[0].mission.steps.s1.meta.fidelityTargetKey = 'unknown_01'; assert.equal(validateFullDraft(value).ready, false); value.missions[0].mission.steps.s1.meta.fidelityTargetKey = 'crisis_01'; assert.equal(validateFullDraft(value).ready, false); delete value.missions[0].mission.steps.s1.meta.fidelityTargetKey; value.missions[0].mission.steps.s1.choices.A.meta.bipComponent = 'Crisis'; assert.equal(validateFullDraft(value).ready, false); });

test('full-draft RPC is read-only, dedicated, and does not require published content', async () => { const sql = await readFile(new URL('../supabase/migrations/20260822020000_research_admin_full_draft_game_preview.sql', import.meta.url), 'utf8'); assert.match(sql, /research_admin_full_draft_game_preview\(target_case_code text\)/); assert.match(sql, /is_research_admin\(\)/); assert.match(sql, /c\.active = false[\s\S]*p\.active = false/); assert.doesNotMatch(sql, /case_game_content/); assert.doesNotMatch(sql, /\b(?:insert|update|delete)\b/i); });
