import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import { RESOURCE_SECTIONS, buildFullDraftPayload, buildFullDraftSnapshot, validateFullDraft, validateMissionStructure } from './game-draft-validator.mjs';
const require = createRequire(import.meta.url);
const { validateStructure } = require('../scripts/structural-content-validator.js');
const { validateResources } = require('../scripts/resource-content-validator.js');

function mission(id) {
  const steps = {};
  for (let n = 1; n <= 5; n++) steps[`s${n}`] = { text: `Fictional scene ${n}`, hint: 'Review the approved plan.', meta: {}, choices: Object.fromEntries([[10, 'A'], [5, 'B'], [0, 'C']].map(([score, key]) => [key, { text: 'Teacher action', consequence: 'Fictional outcome', wizard: 'Wizard response', feedback: 'Behavioral explanation', score, next: n < 5 ? `s${n + 1}` : null, ...(n === 5 ? { ending: score === 10 ? 'STRONG' : score === 5 ? 'MIXED' : 'FRAGILE' } : {}), meta: { bipComponent: 'Prevent', mechanism: 'Brief prompt', errorType: score === 10 ? 'none' : 'missed_prevention_opportunity', function: 'escape' } }])) };
  return { id, title: 'Fictional mission', routine: 'Class routine', start: 's1', expectedSteps: 5, steps, endings: { STRONG: { text: 'Strong narrative' }, MIXED: { text: 'Mixed narrative' }, FRAGILE: { text: 'Fragile narrative' } } };
}
function resources() { return { schemaVersion: 1, sections: Object.fromEntries(Object.entries(RESOURCE_SECTIONS).map(([key, title]) => [key, { title, blocks: [{ type: 'paragraph', text: 'Use a calm, brief plan-aligned response.' }] }])) }; }
function workspace() { const missions = []; for (const [type, count] of [['daily', 10], ['wild', 5], ['crisis', 5]]) for (let slot = count; slot; slot--) missions.push({ mission_type: type, slot_number: slot, mission: mission(`${type}_${slot}`) }); return { case: { id: 'case', case_code: 'CASE-998', student_alias: 'River' }, has_crisis_plan: false, setup_draft: { setup: { schemaVersion: 1, bipBriefing: 'Use the approved plan before each fictional mission.', weeklyTeacherReport: { targetBehavior: 'Target response', replacementBehavior: 'Desired response', targetRoutine: 'Class routine' } } }, resource_draft: { resources: resources() }, fidelity_targets: [], missions }; }

test('snapshot and protected payload use latest saved rows, slot sorting, authoritative alias, and null version', () => { const value = workspace(), snapshot = buildFullDraftSnapshot(value), payload = buildFullDraftPayload(value); assert.deepEqual(snapshot.missions.daily.map(item => item.slotNumber), [1,2,3,4,5,6,7,8,9,10]); assert.equal(payload.resources.studentAlias, 'River'); assert.equal(value.resource_draft.resources.studentAlias, undefined); assert.equal(payload.daily_missions[0].id, 'daily_1'); assert.equal(payload.version, null); });
test('complete 10/5/5 saved draft is previewable with human-review warning', () => { const report = validateFullDraft(workspace()); assert.equal(report.blockingCount, 0); assert.equal(report.ready, true); assert(report.categories['PRIVACY & SAFETY'].warnings.length > 0); });
test('setup and specific mission slots are blocking completeness requirements', () => { const value = workspace(); value.setup_draft.setup.bipBriefing = ''; value.missions = value.missions.filter(row => !(row.mission_type === 'daily' && row.slot_number === 4)); const report = validateFullDraft(value); assert.equal(report.ready, false); const messages = Object.values(report.categories).flatMap(category => category.errors.map(item => item.message)); assert(messages.includes('Daily 4 — Not started.')); assert(messages.some(message => /BIP Briefing/.test(message))); assert.doesNotMatch(messages.join(' '),/weekly check-in|Target Routine/i); });
test('browser mission structure rules stay in parity with runtime validator', () => { const valid = { daily: [mission('one')], wildcard: [], crisis: [] }; assert.equal(validateMissionStructure(valid).valid, validateStructure(valid).valid); valid.daily[0].steps.s2.choices.A.next = 'missing'; assert.equal(validateMissionStructure(valid).valid, validateStructure(valid).valid); });
test('strict browser Resource Map behavior stays in parity and privacy/HTML severity differs correctly', () => { const value = workspace(); let report = validateFullDraft(value); assert.equal(report.categories['RESOURCE MAP'].errors.length, 0); assert.equal(validateResources({ ...resources(), studentAlias: 'River' }, { expectedAlias: 'River' }).valid, true); value.resource_draft.resources.sections.bip.blocks[0].text = 'Contact person@example.org'; report = validateFullDraft(value); assert.equal(report.ready, true); assert(report.categories['PRIVACY & SAFETY'].warnings.some(item => /email/.test(item.message))); value.resource_draft.resources.sections.bip.blocks[0].text = '<script>bad()</script>'; assert.equal(validateFullDraft(value).ready, false); });
test('fidelity manifest and no-plan crisis safeguards block unsupported linkage but not Crisis mission type', () => { const value = workspace(); value.fidelity_targets = [{ target_key: 'proactive_01', domain: 'proactive' }]; let report = validateFullDraft(value); assert.equal(report.ready, true); value.missions[0].mission.steps.s1.meta.fidelityTargetKey = 'proactive_02'; report = validateFullDraft(value); assert.equal(report.ready, false); assert(report.categories['FIDELITY LINKS'].errors.some(item => /not active/.test(item.message))); value.missions[0].mission.steps.s1.meta.fidelityTargetKey = 'crisis_01'; assert.equal(validateFullDraft(value).ready, false); delete value.missions[0].mission.steps.s1.meta.fidelityTargetKey; value.missions[0].mission.steps.s1.choices.A.meta.bipComponent = 'Crisis'; assert.equal(validateFullDraft(value).ready, false); });

test('choice response components may differ from a legitimate step-level fidelity target domain', () => { const value = workspace(); value.has_crisis_plan = true; value.fidelity_targets = [{ target_key: 'proactive_01', domain: 'proactive' }]; const step = value.missions[0].mission.steps.s1; step.meta.fidelityTargetKey = 'proactive_01'; step.choices.A.meta.bipComponent = 'Prevent'; step.choices.B.meta.bipComponent = 'Prevent'; step.choices.C.meta.bipComponent = 'Respond'; const report = validateFullDraft(value); assert.equal(report.categories['FIDELITY LINKS'].errors.length, 0); assert.equal(report.ready, true); });

test('final-authoring mission completeness blocks blank participant-facing fields and required metadata', () => { const mutations = [
  ['mission title', mission => { mission.title = ''; }, /Add a mission title/],
  ['scene', mission => { mission.steps.s1.text = ''; }, /Add the scene text/],
  ['teacher action', mission => { mission.steps.s1.choices.A.text = ''; }, /Add the teacher action/],
  ['consequence', mission => { mission.steps.s1.choices.A.consequence = ''; }, /Add what happens next/],
  ['Wizard feedback', mission => { mission.steps.s1.choices.A.wizard = ''; }, /Add Wizard feedback/],
  ['behavioral explanation', mission => { mission.steps.s1.choices.A.feedback = ''; }, /Add the behavioral explanation/],
  ['choice metadata', mission => { mission.steps.s1.choices.A.meta.mechanism = ''; }, /Add the choice mechanism/],
  ['ending narrative', mission => { mission.endings.STRONG.text = ''; }, /Add the STRONG ending narrative/],
  ['expected steps', mission => { mission.expectedSteps = 4; }, /exactly 5 decisions/]
]; for (const [label, mutate, expected] of mutations) { const value = workspace(); mutate(value.missions[0].mission); const report = validateFullDraft(value); assert.equal(report.ready, false, label); assert.match(report.categories['MISSION STRUCTURE'].errors.map(item => item.message).join('\n'), expected, label); } });

test('expectedSteps 5 with five-decision terminal paths passes final mission checks', () => { const report = validateFullDraft(workspace()); assert.equal(report.categories['MISSION STRUCTURE'].errors.length, 0); assert.equal(report.ready, true); });

test('full-draft RPC is read-only, dedicated, and does not require published content', async () => { const sql = await readFile(new URL('../supabase/migrations/20260822020000_research_admin_full_draft_game_preview.sql', import.meta.url), 'utf8'); assert.match(sql, /research_admin_full_draft_game_preview\(target_case_code text\)/); assert.match(sql, /is_research_admin\(\)/); assert.match(sql, /c\.active = false[\s\S]*p\.active = false/); assert.doesNotMatch(sql, /case_game_content/); assert.doesNotMatch(sql, /\b(?:insert|update|delete)\b/i); });

test('legacy weekly report setup metadata is ignored and never blocks Full Draft', () => { const value = workspace(); value.setup_draft.setup.weeklyTeacherReport = { targetBehavior: '', replacementBehavior: '', targetRoutine: '' }; const report = validateFullDraft(value); assert.equal(report.ready, true); assert.doesNotMatch(JSON.stringify(report), /weekly check-in label/i); });
