import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { RESOURCE_SECTIONS, hasUnsupportedResourceBlocks, normalizeResourceMap, renderGameCreation, setupFromWorkspace } from './game-creation-ui.mjs';
const admin = await readFile(new URL('./admin.js', import.meta.url), 'utf8');
const workspace = { case_id:'a', case_code:'CASE-001', student_alias:'Sky', mission_drafts:[], setup_draft:{setup:{schemaVersion:1,bipBriefing:'Saved plan'}}, resource_draft:{resources:{schemaVersion:1,sections:{bip:{title:'Old title',blocks:[{type:'paragraph',text:'Plan'}]}}}} };

test('Game Setup loads saved briefing above Mission Bank and saves through the existing RPC',()=>{const html=renderGameCreation(workspace);assert.ok(html.indexOf('class="builder-section game-setup"')<html.indexOf('class="mission-bank"'));assert.match(html,/id="bip-briefing"[\s\S]*Saved plan/);assert.deepEqual(setupFromWorkspace(workspace),{schemaVersion:1,bipBriefing:'Saved plan'});assert.match(admin,/research_admin_save_game_setup_draft/);assert.match(admin,/target_setup: state\.setupDraft/);});
test('Resource Map normalizes all canonical sections and preserves valid and unsupported blocks',()=>{const resources=normalizeResourceMap(workspace.resource_draft.resources);assert.deepEqual(Object.keys(resources.sections),Object.keys(RESOURCE_SECTIONS));assert.equal(resources.sections.bip.title,'BIP at a Glance');assert.deepEqual(resources.sections.bip.blocks,[{type:'paragraph',text:'Plan'}]);resources.sections.coaching.blocks.push({type:'legacyThing',payload:{keep:true}});assert.equal(hasUnsupportedResourceBlocks(resources),true);const html=renderGameCreation(workspace,null,null,undefined,'',{},'',undefined,resources);for(const [key,[title]] of Object.entries(RESOURCE_SECTIONS)){assert.match(html,new RegExp(`data-section-key="${key}"`));assert.match(html,new RegExp(title));}assert.match(html,/Unsupported legacy Resource Map content/);});
test('all supported blocks and accessible editing controls render while incomplete drafts remain saveable',()=>{const resources=normalizeResourceMap();resources.sections.bip.blocks=[{type:'paragraph',text:''},{type:'list',items:['']},{type:'definitionList',items:[{term:'',definition:''}]},{type:'callout',label:'',text:''}];const html=renderGameCreation(workspace,null,null,undefined,'',{},'',undefined,resources);for(const text of ['Paragraph','Bullet List','Definition List','Callout','Move Up','Move Down','Remove Block','Add item','Add row','Save Resource Map Draft'])assert.match(html,new RegExp(text));assert.match(admin,/research_admin_save_resource_map_draft/);assert.match(admin,/target_resources: state\.resourceDraft/);assert.doesNotMatch(admin,/localStorage|case_game_content/);});
test('case reset clears setup and resource state',async()=>{const {resetMissionAuthoringState}=await import('./game-creation-ui.mjs');const state={setupDraft:{bipBriefing:'A'},resourceDraft:{private:'A'}};resetMissionAuthoringState(state);assert.equal(state.setupDraft,null);assert.equal(state.resourceDraft,null);});

test('protected game chrome and briefing never expose case code or Jordan fallback',async()=>{const [app,engine]=await Promise.all([readFile(new URL('../game/js/app.js',import.meta.url),'utf8'),readFile(new URL('../game/js/engine.js',import.meta.url),'utf8')]);assert.match(app,/textContent = `Study ID: \$\{MR\.participantCode\}`/);assert.doesNotMatch(app,/Study ID:[^\n]*Case:/);assert.match(engine,/configuredBriefing \|\| publicDemoBriefing \|\| UNCONFIGURED_BIP_BRIEFING/);assert.match(engine,/fixtureId === 'fictional-public-demo'/);});
