import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { ERROR_TYPES, blankMission, defaultMissionId, draftPreviewUrl, latestDraft, nextStepId, normalizeMission, renderGameCreation, renderMissionBank, renderMissionBuilder, resetMissionAuthoringState, stepId } from './game-creation-ui.mjs';
const { validateStructure } = createRequire(import.meta.url)('../scripts/structural-content-validator.js');

const workspace = { case_id:'case-1', case_code:'CASE-998', student_alias:'Star', has_crisis_plan:false, active_fidelity_targets:[{target_key:'proactive_01',description:'Give attention',domain:'Prevent'}], mission_drafts:[{mission_type:'daily',slot_number:1,created_at:'2026-08-21T17:30:00Z',mission:{id:'EXISTING',title:'Circle Time',steps:{}}}], resource_draft:{revision_id:'r1'} };

test('mission bank renders all slots and maps Mystery to wild',()=>{const html=renderMissionBank(workspace);assert.equal((html.match(/data-mission-type="daily"/g)||[]).length,10);assert.equal((html.match(/data-mission-type="wild"/g)||[]).length,5);assert.equal((html.match(/data-mission-type="crisis"/g)||[]).length,5);assert.match(html,/Mystery 1/);assert.match(html,/Formal crisis plan not present/);});
test('existing slot resolves latest mission while new slot gets deterministic blank runtime object',()=>{assert.equal(latestDraft(workspace,'daily',1).mission.id,'EXISTING');assert.equal(latestDraft(workspace,'daily',2),undefined);const mission=blankMission(workspace.case_code,'wild',2);assert.equal(mission.id,'CASE998_M02');assert.equal(defaultMissionId('CASE-998','crisis',1),'CASE998_C01');assert.equal(mission.expectedSteps,5);assert.equal(mission.start,'d1_start');assert.equal(Object.keys(mission.steps).length,13);});
test('decision IDs and next trajectories are controlled and valid',()=>{assert.equal(stepId(1),'d1_start');assert.equal(nextStepId(1,'supported'),'d2_supported');assert.equal(nextStepId(3,'wobbly'),'d4_wobbly');assert.equal(nextStepId(4,'escalated'),'d5_escalated');assert.equal(nextStepId(5,'supported'),null);});
test('builder has setup, approved target controls, branches, fixed scores, endings, and no editable score',()=>{const mission=blankMission(workspace.case_code,'daily',2);const html=renderMissionBuilder(workspace,{mission_type:'daily',slot_number:2},mission,{decision:2,branch:'wobbly'});for(const label of ['MISSION ID','MISSION TITLE','MISSION TYPE','ROUTINE / LOCATION','CENTRAL TENSION','FUNCTION PRESSURE','ACTIVE BIP COMPONENTS','MISSION AUTHORING FOCUS / DESIGN GOAL'])assert.match(html,new RegExp(label));assert.match(html,/proactive_01/);assert.doesNotMatch(html,/name="fidelityTargetKey"[^>]*type="text"/);assert.match(html,/Supported/);assert.match(html,/Wobbly/);assert.match(html,/Escalated/);assert.equal((html.match(/class="choice-card"/g)||[]).length,3);assert.match(html,/type="hidden" name="score" value="10"/);assert.doesNotMatch(html,/type="number"/);assert.match(html,/Mission Endings/);});
test('consequence keeps its runtime name while Error Type uses every controlled option',()=>{const html=renderMissionBuilder(workspace,{mission_type:'daily',slot_number:2},blankMission(workspace.case_code,'daily',2));assert.match(html,/WHAT HAPPENS NEXT\?[\s\S]*name="consequence"/);assert.doesNotMatch(html,/IMMEDIATE MODELED CONSEQUENCE/);assert.match(html,/ERROR TYPE<select name="errorType">/);assert.doesNotMatch(html,/ERROR TYPE<input/);for(const option of ERROR_TYPES){assert.match(html,new RegExp(`value="${option.value}"`));}});
test('legacy Error Types normalize and unknown values remain selectable',()=>{for(const [legacy,canonical] of [['missed active ingredient','missed_active_ingredient'],['missed prevention opportunity','missed_prevention_opportunity'],['missed teaching opportunity','missed_teaching_opportunity'],['missed reinforcement opportunity','missed_reinforcement_opportunity'],['delayed reinforcement','timing_or_delay'],['reinforcement delayed','timing_or_delay'],['reinforces target pattern','reinforces_target_pattern']]){const mission=normalizeMission({steps:{d1_start:{choices:{A:{meta:{errorType:legacy}}}}}},workspace.case_code,'daily',1);assert.equal(mission.steps.d1_start.choices.A.meta.errorType,canonical);}const custom=normalizeMission({steps:{d1_start:{choices:{A:{meta:{errorType:'case specific old value'}}}}}},workspace.case_code,'daily',1);assert.equal(custom.steps.d1_start.choices.A.meta.errorType,'case specific old value');assert.match(renderMissionBuilder(workspace,{mission_type:'daily',slot_number:2},custom),/Existing specific value: case specific old value/);});
test('saved-draft preview availability and URL are metadata-only',()=>{const unsaved=renderMissionBuilder(workspace,{mission_type:'daily',slot_number:2},blankMission(workspace.case_code,'daily',2));assert.match(unsaved,/id="preview-saved-draft"[^>]*disabled/);assert.match(unsaved,/Save this mission before previewing/);const saved=renderMissionBuilder(workspace,{mission_type:'daily',slot_number:1},normalizeMission(workspace.mission_drafts[0].mission,workspace.case_code,'daily',1));assert.doesNotMatch(saved,/id="preview-saved-draft"[^>]*disabled/);assert.match(saved,/Preview uses the last saved version\. Unsaved changes are not included\./);const url=draftPreviewUrl('CASE-998','wild',2),parsed=new URL(url,'https://example.test/research-admin/');assert.deepEqual([...parsed.searchParams.keys()],['qa_case','qa_draft_type','qa_draft_slot']);assert.equal(parsed.search,'?qa_case=CASE-998&qa_draft_type=wild&qa_draft_slot=2');assert.doesNotMatch(url,/mission|student|choice|consequence/i);});
test('selected mission is clearly labeled and its bank slot remains accessible and visibly selected',()=>{const selection={mission_type:'wild',slot_number:2};const bank=renderMissionBank(workspace,selection),builder=renderMissionBuilder(workspace,selection,blankMission(workspace.case_code,'wild',2));assert.match(bank,/class="mission-slot selected"[^>]*data-mission-type="wild"[^>]*data-slot-number="2"[^>]*aria-pressed="true"/);assert.match(builder,/EDITING MISSION[\s\S]*<h2>Mystery 2<\/h2>/);});
test('browser mission uses canonical runtime contract and passes the existing structural validator',()=>{const mission=blankMission(workspace.case_code,'daily',1),step=mission.steps.d1_start;step.text='Scene';step.meta.fidelityTargetKey='proactive_01';assert.equal('scene' in step,false);assert.deepEqual(Object.keys(step.choices),['A','B','C']);assert.deepEqual(Object.values(step.choices).map(choice=>choice.score),[10,5,0]);step.choices.A.feedback='Why';step.choices.A.meta={bipComponent:'Prevent',mechanism:'NCA',errorType:'none',function:'attention'};assert.equal('explanation' in step.choices.A,false);assert.equal(step.choices.A.meta.function,'attention');assert.equal(step.choices.A.next,'d2_supported');assert.equal(mission.expectedSteps,5);assert.equal(mission.start,'d1_start');for(const branch of ['supported','wobbly','escalated'])for(const choice of Object.values(mission.steps[`d5_${branch}`].choices)){assert.equal(choice.next,null);assert.ok(['STRONG','MIXED','FRAGILE'].includes(choice.ending));}assert.deepEqual(validateStructure({daily:[mission]}),{valid:true,errors:[]});});
test('normalization upgrades the early preview format and emits only canonical fields',()=>{const mission=normalizeMission({id:'PARTIAL',title:'Started',centralTension:'Pressure',steps:{d1_start:{scene:'Only this',choices:[{score:99,text:'Try',explanation:'Because',bipComponent:'Prevent',mechanism:'NCA',errorType:'none',function:'attention'}]}}},workspace.case_code,'daily',1),choice=mission.steps.d1_start.choices.A;assert.equal(mission.steps.d1_start.text,'Only this');assert.equal('scene' in mission.steps.d1_start,false);assert.equal(choice.score,10);assert.equal(choice.feedback,'Because');assert.deepEqual(choice.meta,{bipComponent:'Prevent',mechanism:'NCA',errorType:'none',function:'attention'});for(const key of ['explanation','bipComponent','mechanism','errorType','function'])assert.equal(key in choice,false);assert.equal(mission.authoringMeta.centralTension,'Pressure');});
test('primary Game Creation stays draft-only while published QA, signoffs, and orientation remain actionable',()=>{const html=renderGameCreation(workspace,null,null,undefined,'',{case_code:'CASE-998',protected_content:{present:true,version:3},resource_map:{},checklist:{}});assert.match(html,/Save Resource Map Draft/);assert.match(html,/Published Game Review/);assert.match(html,/id="preview-protected-game"/);assert.equal((html.match(/class="signoff-action/g)||[]).length,3);assert.match(html,/data-key="intervention_orientation"/);assert.doesNotMatch(html,/Terminal|create-private-case-starter|protected-seed|Publish Game|case_game_content|Send Login|Enable Reminders/);});
test('Game Creation order is Game Setup, Mission Bank, Mission Builder, Resource Map, Published Game Review',()=>{const html=renderGameCreation(workspace,{mission_type:'daily',slot_number:1},normalizeMission(latestDraft(workspace,'daily',1).mission,workspace.case_code,'daily',1));const positions=['class="builder-section game-setup"','class="mission-bank"','class="mission-builder"','class="builder-section resource-map-builder"','class="published-game-review '].map(marker=>html.indexOf(marker));assert.ok(positions.every(position=>position>=0));assert.deepEqual(positions,[...positions].sort((a,b)=>a-b));});
test('switching cases clears protected mission state while reopening the same case preserves it',()=>{const clientState={selected:{request_id:'case-a'},authoringWorkspace:{case_id:'a'},authoringLoadError:'old error',missionSelection:{mission_type:'daily',slot_number:1},missionDraft:{id:'CASE_A_DRAFT',title:'Private A'},missionNav:{decision:3,branch:'wobbly'},missionMessage:'Draft saved.'};const draft=clientState.missionDraft;const navigate=id=>{if(clientState.selected?.request_id!==id)resetMissionAuthoringState(clientState);clientState.selected={request_id:id};};navigate('case-a');assert.equal(clientState.missionDraft,draft);assert.deepEqual(clientState.missionSelection,{mission_type:'daily',slot_number:1});navigate('case-b');assert.equal(clientState.authoringWorkspace,null);assert.equal(clientState.authoringLoadError,'');assert.equal(clientState.missionSelection,null);assert.equal(clientState.missionDraft,null);assert.deepEqual(clientState.missionNav,{decision:1,branch:'supported'});assert.equal(clientState.missionMessage,'');const caseB={...workspace,case_id:'b',case_code:'CASE-B',mission_drafts:[]};const html=renderGameCreation(caseB,clientState.missionSelection,clientState.missionDraft);assert.doesNotMatch(html,/CASE_A_DRAFT|Private A|Save Draft/);});
