import test from 'node:test';
import assert from 'node:assert/strict';
import { blankMission, defaultMissionId, latestDraft, nextStepId, normalizeMission, renderGameCreation, renderMissionBank, renderMissionBuilder, stepId } from './game-creation-ui.mjs';

const workspace = { case_id:'case-1', case_code:'CASE-998', student_alias:'Star', has_crisis_plan:false, active_fidelity_targets:[{target_key:'proactive_01',description:'Give attention',domain:'Prevent'}], mission_drafts:[{mission_type:'daily',slot_number:1,created_at:'2026-08-21T17:30:00Z',mission:{id:'EXISTING',title:'Circle Time',steps:{}}}], resource_draft:{revision_id:'r1'} };

test('mission bank renders all slots and maps Mystery to wild',()=>{const html=renderMissionBank(workspace);assert.equal((html.match(/data-mission-type="daily"/g)||[]).length,10);assert.equal((html.match(/data-mission-type="wild"/g)||[]).length,5);assert.equal((html.match(/data-mission-type="crisis"/g)||[]).length,5);assert.match(html,/Mystery 1/);assert.match(html,/Formal crisis plan not present/);});
test('existing slot resolves latest mission while new slot gets deterministic blank runtime object',()=>{assert.equal(latestDraft(workspace,'daily',1).mission.id,'EXISTING');assert.equal(latestDraft(workspace,'daily',2),undefined);const mission=blankMission(workspace.case_code,'wild',2);assert.equal(mission.id,'CASE998_M02');assert.equal(defaultMissionId('CASE-998','crisis',1),'CASE998_C01');assert.equal(mission.expectedSteps,5);assert.equal(mission.start,'d1_start');assert.equal(Object.keys(mission.steps).length,13);});
test('decision IDs and next trajectories are controlled and valid',()=>{assert.equal(stepId(1),'d1_start');assert.equal(nextStepId(1,'supported'),'d2_supported');assert.equal(nextStepId(3,'wobbly'),'d4_wobbly');assert.equal(nextStepId(4,'escalated'),'d5_escalated');assert.equal(nextStepId(5,'supported'),null);});
test('builder has setup, approved target controls, branches, fixed scores, endings, and no editable score',()=>{const mission=blankMission(workspace.case_code,'daily',2);const html=renderMissionBuilder(workspace,{mission_type:'daily',slot_number:2},mission,{decision:2,branch:'wobbly'});for(const label of ['MISSION ID','MISSION TITLE','MISSION TYPE','ROUTINE / LOCATION','CENTRAL TENSION','FUNCTION PRESSURE','ACTIVE BIP COMPONENTS','MISSION AUTHORING FOCUS / DESIGN GOAL'])assert.match(html,new RegExp(label));assert.match(html,/proactive_01/);assert.doesNotMatch(html,/name="fidelityTargetKey"[^>]*type="text"/);assert.match(html,/Supported/);assert.match(html,/Wobbly/);assert.match(html,/Escalated/);assert.equal((html.match(/class="choice-card"/g)||[]).length,3);assert.match(html,/type="hidden" name="score" value="10"/);assert.doesNotMatch(html,/type="number"/);assert.match(html,/Mission Endings/);});
test('decision 1 has one scene and decision 5 uses endings with null next',()=>{const mission=blankMission(workspace.case_code,'daily',1);assert.deepEqual(Object.keys(mission.steps).filter(key=>key.startsWith('d1')),['d1_start']);for(const branch of ['supported','wobbly','escalated'])assert.equal(mission.steps[`d5_${branch}`].choices.every(choice=>choice.next===null),true);const html=renderMissionBuilder(workspace,{mission_type:'daily',slot_number:1},mission,{decision:5,branch:'supported'});assert.match(html,/name="ending"/);assert.doesNotMatch(html,/name="trajectory"/);});
test('normalization preserves incomplete existing drafts and fixes score integrity',()=>{const mission=normalizeMission({id:'PARTIAL',title:'Started',steps:{d1_start:{scene:'Only this',choices:[{score:99,text:'Try'}]}}},workspace.case_code,'daily',1);assert.equal(mission.steps.d1_start.scene,'Only this');assert.equal(mission.steps.d1_start.choices[0].score,10);assert.equal(mission.steps.d2_supported.scene,'');});
test('primary Game Creation is draft-only and resource map remains a placeholder',()=>{const html=renderGameCreation(workspace,null,null);assert.match(html,/Browser editor coming next/);assert.match(html,/Draft exists/);assert.doesNotMatch(html,/Terminal|create-private-case-starter|protected-seed|Publish Game|case_game_content|Send Login|Enable Reminders/);});
