import assert from 'node:assert/strict';
import fs from 'node:fs';
import {qualification,coverage,mayAssignPrimary,mayAssignSecondary,ioaDisplay,correctionEvent} from './observations-model.mjs';
import {newObservationForm,renderPhaseObservationWorkspace,renderObservationSetup,renderObserverTeam} from './observations-ui.mjs';
const schema=fs.readFileSync(new URL('../supabase/migrations/20260819010000_classroom_observation_summaries.sql',import.meta.url),'utf8');
const cleanup=fs.readFileSync(new URL('../supabase/migrations/20260819030000_research_admin_cleanup_2b.sql',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('./admin.js',import.meta.url),'utf8');
const e=x=>String(x??'');
assert.deepEqual(coverage(10,2),{completed:10,paired:2,percent:20,required:2,additional:0,meets:true});
assert.equal(qualification({teacher_fidelity_agreement:85,student_behavior_agreement:85}),true);
assert.equal(mayAssignPrimary({active:true,observer_type:'primary_researcher'}),true);
assert.equal(mayAssignSecondary({active:true,observer_type:'trained_observer',status:'qualified'}),true);
assert.equal(ioaDisplay({overall_ioa_attention:true,teacher_fidelity_ioa_percent:80,student_behavior_ioa_percent:90}),'Needs recalibration');
assert.equal(correctionEvent({summary_revision_number:2,summary_recorded_at:'2026-08-19'}),'2026-08-19');

const form=newObservationForm({},true,[{id:'p',observer_code:'JO'}],[{id:'s',observer_code:'JM'}],e,{id:'record-baseline-observation-form',heading:'Record Baseline Observation'});
assert.match(form,/Record Baseline Observation[\s\S]*Teacher fidelity %[\s\S]*Student target behavior %[\s\S]*Was IOA collected\?/);
assert.doesNotMatch(form,/interval-cell|fidelity-entry|implemented_as_written|120 intervals/);
const row={id:'summary',observation_date:'2026-08-18',phase:'baseline',session_number:1,primary_observer_code:'JO',summary_revision_id:'rev-2',summary_revision_number:2,summary_recorded_at:'2026-08-19',secondary_observer_id:'s',secondary_observer_code:'JM',teacher_fidelity_percent:76.5,student_target_behavior_percent:10,ioa:{teacher_fidelity_ioa_percent:80,student_behavior_ioa_percent:79,overall_ioa_attention:true}};
const rendered=renderPhaseObservationWorkspace({current_phase:'baseline',protocol:{planned_baseline_observations:6},observation_data:{coverage:{completed:1,ioa:1,percent:100},setups:[{target_routine:'Arrival',target_behavior_definition:'Calls out'}],observers:[],observations:[row]}},'baseline',e);
assert.match(rendered,/Completed observations in this phase[\s\S]*1[\s\S]*Latest teacher fidelity in this phase[\s\S]*76\.5%[\s\S]*Planned minimum[\s\S]*6/);
assert.match(rendered,/Edit Summary[\s\S]*Correction reason/);
assert.doesNotMatch(rendered,/Correct Summary|data-initial-legacy/);
assert.match(rendered,/Teacher fidelity IOA is 80%\. Recalibration required/);
assert.doesNotMatch(form,/name="phase"|Phase<select/);
assert.match(renderObservationSetup({observation_data:{setups:[]}},e),/Observation Setup[\s\S]*Save Observation Setup/);

assert.match(schema,/create function public\.research_admin_record_classroom_observation_summary/);
assert.match(schema,/create function public\.research_admin_revise_classroom_observation_summary/);
assert.match(schema,/select max\(revision_number\)\+1[\s\S]*insert into public\.research_classroom_observation_summary_revisions/);
assert.match(cleanup,/join current_summaries cs on cs\.observation_id=o\.id/);
assert.doesNotMatch(cleanup,/coalesce\(cs\.|current_records|not_calculable/);
assert.match(cleanup,/teacher_fidelity_ioa_percent<=80 or student_behavior_ioa_percent<=80/);
assert.match(cleanup,/teacher_fidelity_agreement>=85 and e\.student_behavior_agreement>=85/);
assert.match(cleanup,/drop table if exists public\.research_classroom_ioa_results;[\s\S]*drop table if exists public\.research_classroom_observation_records;/);
for(const signature of ['research_admin_submit_classroom_observation_record\\(uuid,text,jsonb,jsonb,text,text\\)','research_generate_classroom_ioa\\(uuid\\)','research_admin_create_legacy_observation_summary\\(uuid,numeric,numeric,numeric,numeric,text,text,text\\)']) assert.match(cleanup,new RegExp(`drop function if exists public\\.${signature}`));
assert.doesNotMatch(cleanup,/cascade/i);
assert.match(js,/research_admin_record_classroom_observation_summary/);
assert.match(js,/research_admin_revise_classroom_observation_summary/);
assert.doesNotMatch(js,/research_admin_create_legacy_observation_summary|primary_record_id|secondary_record_id/);
const observerTeam=renderObserverTeam({observers:[{id:'observer',observer_code:'JM',display_name:'Jordan',observer_type:'trained_observer',active:true,status:'recalibration_required',latest_training:{teacher_fidelity_agreement:91,student_behavior_agreement:92},training_history:[]}]},e);
assert.match(observerTeam,/Recalibration required before further independent observation\./);
console.log('Summary-only observation workflow and Cleanup 2B checks passed.');
