export const FIDELITY_STATUSES=['implemented_as_written','not_implemented_as_written','no_opportunity'];
export const INTERVAL_STATUSES=['no_occurrence','occurrence','not_observed'];
export const OBSERVATION_PHASES=['baseline','intervention','maintenance'];
export const TRAINING_THRESHOLD=85, IOA_THRESHOLD=80, IOA_COVERAGE_TARGET=.20, INTERVAL_COUNT=120;
export function fidelitySummary(scores=[]){const implemented=scores.filter(x=>x.status==='implemented_as_written').length,notImplemented=scores.filter(x=>x.status==='not_implemented_as_written').length,noOpportunity=scores.filter(x=>x.status==='no_opportunity').length,scoreable=implemented+notImplemented;return{implemented,notImplemented,noOpportunity,scoreable,percent:scoreable?100*implemented/scoreable:null};}
export function intervalSummary(intervals=[]){const occurrence=intervals.filter(x=>x.status==='occurrence').length,notObserved=intervals.filter(x=>x.status==='not_observed').length,noOccurrence=intervals.filter(x=>x.status==='no_occurrence').length,observed=occurrence+noOccurrence;return{occurrence,noOccurrence,notObserved,observed,percent:observed?100*occurrence/observed:null};}
export function teacherIoa(primary,secondary){const other=new Map(secondary.map(x=>[x.target_key,x.status]));let agreements=0,disagreements=0;for(const x of primary){if(!other.has(x.target_key))continue;if(other.get(x.target_key)===x.status)agreements++;else disagreements++;}return{agreements,disagreements,percent:agreements+disagreements?100*agreements/(agreements+disagreements):null,meets:agreements+disagreements?100*agreements/(agreements+disagreements)>IOA_THRESHOLD:false};}
export function studentIoa(primary,secondary){const other=new Map(secondary.map(x=>[x.interval_number,x.status]));let agreements=0,disagreements=0,excluded=0;for(const x of primary){const status=other.get(x.interval_number);if(!status)continue;if(x.status==='not_observed'||status==='not_observed'){excluded++;continue;}if(x.status===status)agreements++;else disagreements++;}return{agreements,disagreements,excluded,percent:agreements+disagreements?100*agreements/(agreements+disagreements):null,meets:agreements+disagreements?100*agreements/(agreements+disagreements)>IOA_THRESHOLD:false};}
export function qualification(event){return Boolean(event&&event.teacher_fidelity_agreement>=TRAINING_THRESHOLD&&event.student_behavior_agreement>=TRAINING_THRESHOLD);}
export function coverage(completed,paired){const required=Math.ceil(completed*IOA_COVERAGE_TARGET);return{completed,paired,percent:completed?100*paired/completed:0,required,additional:Math.max(required-paired,0),meets:paired>=required};}
export function defaultIntervals(){return Array.from({length:INTERVAL_COUNT},(_,i)=>({interval_number:i+1,status:'no_occurrence'}));}
export function observationAttention(item){const data=item.observation_data||{},c=data.coverage||{},rows=data.observations||[],out=[];if(item.current_phase!=='prebaseline'&&!(data.setups||[]).length)out.push('Observation setup missing after baseline begins');if(rows.some(x=>!x.primary_record_id))out.push('Primary observation record incomplete');if(rows.some(x=>x.secondary_observer_id&&!x.secondary_record_id))out.push('Secondary record pending for an IOA-designated session');if((c.completed||0)>0&&(c.percent||0)<20)out.push('Classroom IOA coverage currently below 20%');if(rows.some(x=>x.ioa?.overall_ioa_attention))out.push('Classroom IOA ≤80%');if((data.observers||[]).some(x=>x.status==='recalibration_required'))out.push('Observer recalibration required');const baseline=rows.filter(x=>x.phase==='baseline'&&x.primary_record_id).length;if(item.current_phase==='baseline'&&item.protocol&&baseline<item.protocol.planned_baseline_observations)out.push('Baseline observation count below assigned planned minimum');return out;}
