import { denverWeek } from './observations-model.mjs';
const pct=value=>value===null||value===undefined?'Not enough data':`${Number(value).toFixed(1).replace(/\.0$/,'')}%`;
const checked=condition=>condition?' checked':'';
const dateLabel=value=>{const date=new Date(`${value}T12:00:00Z`);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(date);};
const timeLabel=value=>{if(!value)return '';const [hour,minute]=value.slice(0,5).split(':').map(Number);return `${hour%12||12}:${String(minute).padStart(2,'0')} ${hour<12?'AM':'PM'}`;};

export function renderObserverTeam(data,e){
 const rows=(data.observers||[]).map(observer=>`<li><form class="observer-edit-form compact-form" data-id="${observer.id}"><label>Code<input name="code" maxlength="16" value="${e(observer.observer_code)}" required></label><label>Display name<input name="name" maxlength="160" value="${e(observer.display_name)}" required></label><input type="hidden" name="type" value="${observer.observer_type}"><label class="check-option"><input type="checkbox" name="active"${checked(observer.active)}> Active</label><span><strong>${e(observer.observer_type.replaceAll('_',' '))}</strong> · <span class="${observer.status==='qualified'?'ready':'needs'}">${e(observer.status.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()))}</span></span><button class="quiet">Save observer</button></form>${observer.latest_training?`<p>Teacher fidelity practice agreement: ${pct(observer.latest_training.teacher_fidelity_agreement)} · Student behavior practice agreement: ${pct(observer.latest_training.student_behavior_agreement)}</p>`:''}${observer.status==='recalibration_required'?'<p class="attention">Recalibration required before further independent observation.</p>':''}<details><summary>Training history</summary><ol>${(observer.training_history||[]).map(x=>`<li>${e(x.event_date)} · ${e(x.event_type)} · Teacher ${pct(x.teacher_fidelity_agreement)} · Student ${pct(x.student_behavior_agreement)}</li>`).join('')||'<li>No events.</li>'}</ol></details></li>`).join('')||'<li>No observers registered.</li>';
 return `<section class="panel observer-team"><p class="eyebrow">Observers</p><h2>Observer Team</h2><p>Inactive observers stay in the record so old data keeps the correct observer.</p><p id="observer-message" class="success-message" role="status" aria-live="polite"></p><form id="observer-form" class="compact-form"><label>Observer code<input name="code" maxlength="16" required></label><label>Display name<input name="name" maxlength="160" required></label><label>Observer type<select name="type"><option value="trained_observer">Trained observer</option><option value="primary_researcher">Primary researcher</option></select></label><button class="primary">Add observer</button></form><form id="training-form" class="compact-form"><h3>Observer Training</h3><p class="neutral-note">To collect IOA independently, an observer needs ≥85% on both teacher fidelity and student behavior during Practice, Recalibration, or Retraining.</p><label>Observer<select name="observer_id" required><option value="">Select</option>${(data.observers||[]).filter(x=>x.observer_type==='trained_observer').map(x=>`<option value="${x.id}">${e(x.observer_code)}</option>`).join('')}</select></label><label>Event<select name="event_type">${['training','practice','recalibration','retraining'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Date<input type="date" name="event_date" required></label><label>Teacher fidelity agreement %<input type="number" name="teacher" min="0" max="100" step="any" required></label><label>Student behavior agreement %<input type="number" name="student" min="0" max="100" step="any" required></label><label>Note — optional<textarea name="note" maxlength="1000"></textarea></label><button class="primary">Save Training Record</button></form><ul>${rows}</ul></section>`;
}

export function renderStudyIoaSummary(data,e){const c=data.coverage||{};return `<section class="panel study-ioa-summary"><p class="eyebrow">IOA</p><h2>Study IOA</h2><div class="observation-stats"><div><span>Completed observations</span><strong>${c.completed||0}</strong></div><div><span>IOA Coverage</span><strong>${pct(c.percent||0)}</strong></div></div><ul>${(data.by_dyad||[]).map(x=>`<li>${e(x.study_id)}: ${x.ioa} / ${x.completed}, ${pct(x.percent)}</li>`).join('')||'<li>No finalized observations.</li>'}</ul></section>`;}

export function newObservationForm(item,setup,primaryOptions,secondaryOptions,e){
 return `<form id="record-observation-form" class="observation-summary-form"><h3>Record Observation</h3>${setup?'':'<p class="attention">Save Observation Setup before recording an observation.</p>'}<h4>Observation Details</h4><div class="summary-form-grid"><label>Date<input name="date" type="date" required></label><label>Primary observer<select name="primary" required><option value="">Select</option>${primaryOptions.map(x=>`<option value="${x.id}">${e(x.observer_code)}</option>`).join('')}</select></label><label>Start time — optional<input name="start" type="time"></label><label>End time — optional<input name="end" type="time"></label><p class="phase-helper">Phase: <strong>Choose a date</strong></p><label class="wide">Observation note — optional<textarea name="note" maxlength="1000"></textarea></label></div><h4>Observation Results</h4><div class="summary-form-grid"><label>Teacher fidelity %<input name="teacher_fidelity_percent" type="number" min="0" max="100" step="any" required></label><label>Student target behavior %<input name="student_target_behavior_percent" type="number" min="0" max="100" step="any" required></label></div><h4>IOA</h4><fieldset class="ioa-choice"><legend>Was IOA collected?</legend><label><input type="radio" name="ioa_collected" value="no" checked> No</label><label><input type="radio" name="ioa_collected" value="yes"> Yes</label></fieldset><div class="summary-form-grid ioa-fields" hidden><label>IOA observer<select name="secondary"><option value="">Select</option>${secondaryOptions.map(x=>`<option value="${x.id}">${e(x.observer_code)}</option>`).join('')}</select></label><label>Teacher fidelity IOA %<input name="teacher_fidelity_ioa_percent" type="number" min="0" max="100" step="any"></label><label>Student behavior IOA %<input name="student_behavior_ioa_percent" type="number" min="0" max="100" step="any"></label><label>IOA note — optional<textarea name="ioa_note" maxlength="1000"></textarea></label></div><button class="primary"${setup?'':' disabled'}>Save Observation</button></form>`;
}

function editSummaryForm(x,e){return `<form class="edit-summary-form summary-form-grid" data-observation="${x.id}" data-initial-legacy="${!x.summary_revision_id}" hidden><label>Teacher fidelity %<input name="teacher_fidelity_percent" type="number" min="0" max="100" step="any" value="${x.teacher_fidelity_percent}" required></label><label>Student target behavior %<input name="student_target_behavior_percent" type="number" min="0" max="100" step="any" value="${x.student_target_behavior_percent}" required></label>${x.secondary_record_id?`<label>Teacher fidelity IOA %<input name="teacher_fidelity_ioa_percent" type="number" min="0" max="100" step="any" value="${x.ioa?.teacher_fidelity_ioa_percent??''}" required></label><label>Student behavior IOA %<input name="student_behavior_ioa_percent" type="number" min="0" max="100" step="any" value="${x.ioa?.student_behavior_ioa_percent??''}" required></label><label>IOA note — optional<textarea name="ioa_note" maxlength="1000">${e(x.ioa_note||'')}</textarea></label>`:''}<label class="wide">Observation note — optional<textarea name="observation_note" maxlength="1000">${e(x.summary_observation_note||x.context_note||'')}</textarea></label><label class="wide">Correction reason<input name="correction_reason" maxlength="1000" required></label><button class="primary">Save Correction</button></form>`;}

export function renderObservations(item,e){
 const data=item.observation_data||{},setup=(data.setups||[])[0],observers=data.observers||[],rows=data.observations||[],coverage=data.coverage||{};
 const completed=rows.filter(x=>x.primary_record_id),baseline=completed.filter(x=>x.phase==='baseline').length,maintenance=completed.filter(x=>x.phase==='maintenance').length,latest=completed[0];
 const history=rows.map(x=>{const note=x.summary_observation_note||x.context_note;const time=x.start_time||x.end_time?`${timeLabel(x.start_time)||'—'}–${timeLabel(x.end_time)||'—'} · `:'';const alerts=[];if(x.ioa?.teacher_fidelity_ioa_percent!=null&&Number(x.ioa.teacher_fidelity_ioa_percent)<=80)alerts.push(`Needs review — Teacher fidelity IOA is ${pct(x.ioa.teacher_fidelity_ioa_percent)}. Recalibration required.`);if(x.ioa?.student_behavior_ioa_percent!=null&&Number(x.ioa.student_behavior_ioa_percent)<=80)alerts.push(`Needs review — Student behavior IOA is ${Number(x.ioa.student_behavior_ioa_percent)===80?'80%':'below criterion'}. Recalibration required.`);return `<li id="observation-${x.id}"><strong>${e(dateLabel(x.observation_date))} · ${e(x.phase[0].toUpperCase()+x.phase.slice(1))} · Observation #${x.session_number}</strong><p>${time}${e(x.primary_observer_code)}</p><p>Teacher fidelity: <strong>${pct(x.teacher_fidelity_percent)}</strong><br>Student target behavior: <strong>${pct(x.student_target_behavior_percent)}</strong></p>${x.secondary_record_id?`<p>IOA: ${e(x.secondary_observer_code)}<br>Teacher fidelity IOA: ${pct(x.ioa?.teacher_fidelity_ioa_percent)}<br>Student behavior IOA: ${pct(x.ioa?.student_behavior_ioa_percent)}</p>`:'<p>IOA: Not collected</p>'}${alerts.map(a=>`<p class="attention">${a}</p>`).join('')}${note?`<p>Notes: ${e(note)}</p>`:''}<button type="button" class="quiet edit-summary-toggle" data-observation="${x.id}">${x.summary_revision_id?'Edit Summary':'Correct Summary'}</button>${editSummaryForm(x,e)}</li>`;}).join('')||'<li>No classroom observations.</li>';
 const primaryOptions=observers.filter(x=>x.active&&(x.observer_type==='primary_researcher'||(x.observer_type==='trained_observer'&&x.status==='qualified'))),secondaryOptions=observers.filter(x=>x.active&&x.observer_type==='trained_observer'&&x.status==='qualified');
 const stats=`<div class="observation-stats"><div><span>Baseline</span><strong>${baseline} / ${item.protocol?.planned_baseline_observations||'not assigned'}</strong></div><div><span>Latest Teacher Fidelity</span><strong>${pct(latest?.teacher_fidelity_percent)}</strong></div><div><span>Latest Student Target Behavior</span><strong>${pct(latest?.student_target_behavior_percent)}</strong></div><div><span>IOA Coverage</span><strong>${coverage.ioa||0} / ${coverage.completed||0} · ${pct(coverage.percent||0)}</strong></div>${item.current_phase==='maintenance'?`<div><span>Maintenance</span><strong>${maintenance} completed probes</strong></div>`:''}</div>`;
 const setupBanner=setup?`<div class="setup-banner"><p class="eyebrow">Observation Setup</p><p><strong>Routine:</strong> ${e(setup.target_routine)}<br><strong>Target behavior:</strong><br>${e(setup.target_behavior_definition)}</p><button type="button" id="edit-observation-setup" class="quiet">Edit</button></div>`:'';
 const setupForm=`<form id="observation-setup-form" class="compact-form"${setup?' hidden':''}><h3>Observation Setup</h3><label>Routine<input name="routine" maxlength="1000" value="${e(setup?.target_routine||'')}" required></label><label>Target behavior definition<textarea name="definition" maxlength="2000" required>${e(setup?.target_behavior_definition||'')}</textarea></label><label>Change note — optional<input name="change_note" maxlength="1000"></label><button class="primary">Save Observation Setup</button></form>`;
 return `<section id="operations-observations" class="panel observations-ioa operations-section"><p class="eyebrow">Observations</p><h2>Classroom Observations &amp; IOA</h2>${stats}${setupBanner}${setupForm}${newObservationForm(item,setup,primaryOptions,secondaryOptions,e)}<h3>Observation History</h3><ol class="observation-history">${history}</ol></section>`;
}

export function recordPayload(form){const f=new FormData(form);return {teacher_fidelity_percent:Number(f.get('teacher_fidelity_percent')),student_target_behavior_percent:Number(f.get('student_target_behavior_percent')),teacher_fidelity_ioa_percent:f.get('teacher_fidelity_ioa_percent')===''?null:Number(f.get('teacher_fidelity_ioa_percent')),student_behavior_ioa_percent:f.get('student_behavior_ioa_percent')===''?null:Number(f.get('student_behavior_ioa_percent'))};}
