export const FIDELITY_STATUSES=['implemented_as_written','not_implemented_as_written','no_opportunity'];
export const INTERVAL_STATUSES=['no_occurrence','occurrence','not_observed'];
export const OBSERVATION_PHASES=['baseline','intervention','maintenance'];
export const TRAINING_THRESHOLD=85, IOA_THRESHOLD=80, IOA_COVERAGE_TARGET=.20, INTERVAL_COUNT=120;
export function fidelitySummary(scores=[]){const implemented=scores.filter(x=>x.status==='implemented_as_written').length,notImplemented=scores.filter(x=>x.status==='not_implemented_as_written').length,noOpportunity=scores.filter(x=>x.status==='no_opportunity').length,scoreable=implemented+notImplemented;return{implemented,notImplemented,noOpportunity,scoreable,percent:scoreable?100*implemented/scoreable:null};}
export function intervalSummary(intervals=[]){const occurrence=intervals.filter(x=>x.status==='occurrence').length,notObserved=intervals.filter(x=>x.status==='not_observed').length,noOccurrence=intervals.filter(x=>x.status==='no_occurrence').length,observed=occurrence+noOccurrence;return{occurrence,noOccurrence,notObserved,observed,percent:observed?100*occurrence/observed:null};}
export function teacherIoa(primary,secondary){const other=new Map(secondary.map(x=>[x.target_key,x.status]));let agreements=0,disagreements=0;for(const x of primary){if(!other.has(x.target_key))continue;if(other.get(x.target_key)===x.status)agreements++;else disagreements++;}return{agreements,disagreements,percent:agreements+disagreements?100*agreements/(agreements+disagreements):null,meets:agreements+disagreements?100*agreements/(agreements+disagreements)>IOA_THRESHOLD:false};}
export function studentIoa(primary,secondary){const other=new Map(secondary.map(x=>[x.interval_number,x.status]));let agreements=0,disagreements=0,excluded=0;for(const x of primary){const status=other.get(x.interval_number);if(!status)continue;if(x.status==='not_observed'||status==='not_observed'){excluded++;continue;}if(x.status===status)agreements++;else disagreements++;}return{agreements,disagreements,excluded,percent:agreements+disagreements?100*agreements/(agreements+disagreements):null,meets:agreements+disagreements?100*agreements/(agreements+disagreements)>IOA_THRESHOLD:false};}
export function qualification(event){return Boolean(event&&event.teacher_fidelity_agreement>=TRAINING_THRESHOLD&&event.student_behavior_agreement>=TRAINING_THRESHOLD);}
export function coverage(completed,paired){const required=Math.ceil(completed*IOA_COVERAGE_TARGET);return{completed,paired,percent:completed?100*paired/completed:0,required,additional:Math.max(required-paired,0),meets:paired>=required};}
export function defaultIntervals(){return Array.from({length:INTERVAL_COUNT},(_,i)=>({interval_number:i+1,status:'no_occurrence'}));}
export function observationAttention(item){const data=item.observation_data||{},c=data.coverage||{},rows=data.observations||[],out=[];if(item.current_phase!=='prebaseline'&&!(data.setups||[]).length)out.push('Observation setup missing after baseline begins');if(rows.some(x=>!x.primary_record_id))out.push('Primary observation record incomplete');if(rows.some(x=>x.secondary_observer_id&&!x.secondary_record_id))out.push('Secondary record pending for an IOA-designated session');if((c.completed||0)>0&&(c.percent||0)<20)out.push('Classroom IOA coverage currently below 20%');if(rows.some(x=>x.ioa?.overall_ioa_attention))out.push('Classroom IOA ≤80%');if((data.observers||[]).some(x=>x.status==='recalibration_required'))out.push('Observer recalibration required');const baseline=rows.filter(x=>x.phase==='baseline'&&x.primary_record_id).length;if(item.current_phase==='baseline'&&item.protocol&&baseline<item.protocol.planned_baseline_observations)out.push('Baseline observation count below assigned planned minimum');return out;}

export function denverWeek(now=new Date()){const date=new Date(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)+'T12:00:00Z'),day=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-day);const monday=date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()+6);return{monday,sunday:date.toISOString().slice(0,10)};}
export function ioaDisplay(ioa){if(!ioa)return null;if(ioa.overall_ioa_attention)return 'Needs recalibration';if(ioa.teacher_fidelity_ioa_percent==null||ioa.student_behavior_ioa_percent==null)return 'IOA not calculable / review';return 'Meets criterion';}
export function recalibrationState(low,good){if(!low)return 'qualified';if(!good)return 'recalibration_required';return [good.date,good.recorded_at].join('|')>[low.date,low.recorded_at].join('|')?'qualified':'recalibration_required';}
export function mayAssignPrimary(observer){return Boolean(observer?.active&&(observer.observer_type==='primary_researcher'||(observer.observer_type==='trained_observer'&&observer.status==='qualified')));}
export function mayAssignSecondary(observer){return Boolean(observer?.active&&observer.observer_type==='trained_observer'&&observer.status==='qualified');}
export function ioaNeedsReview(ioa){return Boolean(ioa&&(ioa.overall_ioa_attention||ioa.teacher_fidelity_ioa_percent==null||ioa.student_behavior_ioa_percent==null));}
export function correctionEvent(observation){const records=[observation?.primary_record,observation?.secondary_record].filter(record=>(record?.revision_number||1)>1&&record.submitted_at);if(!records.length)return null;return records.sort((a,b)=>String(b.submitted_at).localeCompare(String(a.submitted_at)))[0].submitted_at;}
