export const TRAINING_THRESHOLD=85, IOA_THRESHOLD=80, IOA_COVERAGE_TARGET=.20;
export function qualification(event){return Boolean(event&&event.teacher_fidelity_agreement>=TRAINING_THRESHOLD&&event.student_behavior_agreement>=TRAINING_THRESHOLD);}
export function coverage(completed,paired){const required=Math.ceil(completed*IOA_COVERAGE_TARGET);return{completed,paired,percent:completed?100*paired/completed:0,required,additional:Math.max(required-paired,0),meets:paired>=required};}
export function observationAttention(item){const data=item.observation_data||{},c=data.coverage||{},rows=data.observations||[],out=[];if(item.current_phase!=='prebaseline'&&!(data.setups||[]).length)out.push('Observation setup missing after baseline begins');if((c.completed||0)>0&&(c.percent||0)<20)out.push('Classroom IOA coverage currently below 20%');if(rows.some(x=>x.ioa?.overall_ioa_attention))out.push('Classroom IOA ≤80%');if((data.observers||[]).some(x=>x.status==='recalibration_required'))out.push('Observer recalibration required');const baseline=rows.filter(x=>x.phase==='baseline'&&x.summary_revision_id).length;if(item.current_phase==='baseline'&&item.protocol&&baseline<item.protocol.planned_baseline_observations)out.push('Baseline observation count below assigned planned minimum');return out;}

export function denverWeek(now=new Date()){const date=new Date(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)+'T12:00:00Z'),day=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-day);const monday=date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()+6);return{monday,sunday:date.toISOString().slice(0,10)};}
export function ioaDisplay(ioa){if(!ioa)return null;if(ioa.overall_ioa_attention)return 'Needs recalibration';if(ioa.teacher_fidelity_ioa_percent==null||ioa.student_behavior_ioa_percent==null)return 'Needs review';return 'Meets criterion';}
export function recalibrationState(low,good){if(!low)return 'qualified';if(!good)return 'recalibration_required';return [good.date,good.recorded_at].join('|')>[low.date,low.recorded_at].join('|')?'qualified':'recalibration_required';}
export function mayAssignPrimary(observer){return Boolean(observer?.active&&(observer.observer_type==='primary_researcher'||(observer.observer_type==='trained_observer'&&observer.status==='qualified')));}
export function mayAssignSecondary(observer){return Boolean(observer?.active&&observer.observer_type==='trained_observer'&&observer.status==='qualified');}
export function ioaNeedsReview(ioa){return Boolean(ioa&&(ioa.overall_ioa_attention||ioa.teacher_fidelity_ioa_percent==null||ioa.student_behavior_ioa_percent==null));}
export function correctionEvent(observation){return Number(observation?.summary_revision_number)>1?observation.summary_recorded_at:null;}
