import { denverWeek, fidelitySummary, intervalSummary, ioaDisplay } from './observations-model.mjs';
const pct=value=>value===null||value===undefined?'Not enough data':`${Number(value).toFixed(1)}%`;
const checked=(condition)=>condition?' checked':'';

export function intervalGrid(role,current=[]){
  const values=new Map(current.map(x=>[Number(x.interval_number),x.status]));
  return `<div class="interval-grid" data-role="${role}"><span class="grid-head">Minute</span>${['0–15','15–30','30–45','45–60'].map(x=>`<span class="grid-head">${x}</span>`).join('')}${Array.from({length:30},(_,minute)=>`<strong>${minute+1}</strong>${[0,1,2,3].map(quarter=>{const n=minute*4+quarter+1,status=values.get(n)||'no_occurrence',mark=status==='occurrence'?'X':status==='not_observed'?'O':'&nbsp;';return `<button type="button" class="interval-cell" data-interval="${n}" data-status="${status}" aria-label="Minute ${minute+1}, ${quarter*15} to ${(quarter+1)*15} seconds: ${status}">${mark}</button>`;}).join('')}`).join('')}</div>`;
}

export function recordForm(observation,role,e){
  const current=role==='primary'?observation.primary_record:observation.secondary_record;
  const currentScores=new Map((current?.fidelity_scores||[]).map(x=>[x.target_key,x.status]));
  const label=current?`Correct ${role==='primary'?'Primary':'IOA'} Record`:(role==='primary'?'Primary Observer':'IOA Observer');
  const scores=observation.fidelity_items_snapshot.map(item=>`<fieldset data-target="${e(item.target_key)}"><legend>${e(item.domain)} · ${e(item.target_key)} — ${e(item.description)}</legend>${[['implemented_as_written','Implemented as Written'],['not_implemented_as_written','Not Implemented as Written'],['no_opportunity','No Opportunity']].map(([value,text])=>`<label><input type="radio" name="f-${e(item.target_key)}" value="${value}"${checked(currentScores.get(item.target_key)===value)} required> ${text}</label>`).join('')}</fieldset>`).join('');
  return `<form class="observation-record-form" data-observation="${observation.id}" data-role="${role}" data-correction="${Boolean(current)}"><h3>${label}</h3><p><strong>Teacher Fidelity</strong> — score every item.</p><div class="fidelity-entry">${scores}</div><p class="fidelity-preview"></p><h3>Student Target Behavior</h3><p><strong>30 minutes · 15-second intervals · 120 intervals</strong></p><div class="interval-legend"><span><b>X</b> = target behavior occurred</span><span><b>O</b> = not observed</span><span><b>Blank</b> = observed, no target behavior</span></div>${intervalGrid(role,current?.student_intervals)}<p class="interval-preview"></p><label>Observer note — optional<textarea name="observer_note" maxlength="1000">${e(current?.observer_note||'')}</textarea></label><label>Correction reason${current?' — required':''}<input name="correction_reason" maxlength="1000" ${current?'required':''}></label><label class="check-option final-confirm"><input type="checkbox" name="confirmed" required> I checked the fidelity scores and all 120 intervals.</label><button class="primary">${current?'Save Correction':'Save Observation'}</button></form>`;
}

export function renderObserverTeam(data,e){
  const rows=(data.observers||[]).map(observer=>`<li><form class="observer-edit-form compact-form" data-id="${observer.id}"><label>Code<input name="code" maxlength="16" value="${e(observer.observer_code)}" required></label><label>Display name<input name="name" maxlength="160" value="${e(observer.display_name)}" required></label><input type="hidden" name="type" value="${observer.observer_type}"><label class="check-option"><input type="checkbox" name="active"${checked(observer.active)}> Active</label><span><strong>${e(observer.observer_type.replaceAll('_',' '))}</strong> · <span class="${observer.status==='qualified'?'ready':'needs'}">${e(observer.status.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()))}</span></span><button class="quiet">Save observer</button></form>${observer.latest_training?`<p>Teacher fidelity practice agreement: ${pct(observer.latest_training.teacher_fidelity_agreement)} · Student behavior practice agreement: ${pct(observer.latest_training.student_behavior_agreement)}</p>`:''}${observer.status==='recalibration_required'?'<p class="attention">Recalibration required before further independent observation.</p>':''}<details><summary>Training history</summary><ol>${(observer.training_history||[]).map(x=>`<li>${e(x.event_date)} · ${e(x.event_type)} · Teacher ${pct(x.teacher_fidelity_agreement)} · Student ${pct(x.student_behavior_agreement)}</li>`).join('')||'<li>No events.</li>'}</ol></details></li>`).join('')||'<li>No observers registered.</li>';
  return `<section class="panel observer-team"><p class="eyebrow">Observers</p><h2>Observer Team</h2><p>Inactive observers stay in the record so old data keeps the correct observer.</p><p id="observer-message" class="success-message" role="status" aria-live="polite"></p><form id="observer-form" class="compact-form"><label>Observer code<input name="code" maxlength="16" required></label><label>Display name<input name="name" maxlength="160" required></label><label>Observer type<select name="type"><option value="trained_observer">Trained observer</option><option value="primary_researcher">Primary researcher</option></select></label><button class="primary">Add observer</button></form><form id="training-form" class="compact-form"><h3>Observer Training</h3><p class="neutral-note">To collect IOA independently, an observer needs ≥85% on both teacher fidelity and student behavior during Practice, Recalibration, or Retraining.</p><label>Observer<select name="observer_id" required><option value="">Select</option>${(data.observers||[]).filter(x=>x.observer_type==='trained_observer').map(x=>`<option value="${x.id}">${e(x.observer_code)}</option>`).join('')}</select></label><label>Event<select name="event_type">${['training','practice','recalibration','retraining'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Date<input type="date" name="event_date" required></label><label>Teacher fidelity agreement %<input type="number" name="teacher" min="0" max="100" step=".01" required></label><label>Student behavior agreement %<input type="number" name="student" min="0" max="100" step=".01" required></label><label>Note — optional<textarea name="note" maxlength="1000"></textarea></label><button class="primary">Save Training Record</button></form><ul>${rows}</ul></section>`;
}

export function renderStudyIoaSummary(data,e){
  const c=data.coverage||{};
  return `<section class="panel study-ioa-summary"><p class="eyebrow">IOA</p><h2>Study IOA</h2><div class="observation-stats"><div><span>Completed observations</span><strong>${c.completed||0}</strong></div><div><span>IOA observations</span><strong>${c.ioa||0}</strong></div><div><span>IOA Coverage</span><strong>${pct(c.percent||0)}</strong><small>Minimum ${c.required_minimum||0} · ${c.additional_needed||0} additional needed</small></div><div><span>Needs review</span><strong>${(c.teacher_alerts||0)+(c.student_alerts||0)} need review</strong><small>Teacher: ${c.teacher_alerts||0} · Student: ${c.student_alerts||0} · Not enough data: ${c.not_calculable||0}</small></div></div><h3>By dyad</h3><ul>${(data.by_dyad||[]).map(x=>`<li>${e(x.study_id)}: ${x.ioa} / ${x.completed}, ${pct(x.percent)}</li>`).join('')||'<li>No finalized observations.</li>'}</ul><h3>By Phase</h3><ul>${['baseline','intervention','maintenance'].map(phase=>{const x=(data.by_phase||[]).find(row=>row.phase===phase)||{completed:0,ioa:0,percent:0};return `<li>${phase[0].toUpperCase()+phase.slice(1)}: ${x.ioa} / ${x.completed}, ${pct(x.percent)}</li>`;}).join('')}</ul><p>At least 20% of completed observations need IOA across the study.</p></section>`;
}

export function renderObservations(item,e){
  const data=item.observation_data||{},setup=(data.setups||[])[0],observers=data.observers||[],rows=data.observations||[],coverage=data.coverage||{};
  const baseline=rows.filter(x=>x.phase==='baseline'&&x.primary_record_id).length,maintenance=rows.filter(x=>x.phase==='maintenance'&&x.primary_record_id).length;
  const {monday,sunday}=denverWeek(),weekCount=rows.filter(x=>x.phase==='intervention'&&x.primary_record_id&&x.observation_date>=monday&&x.observation_date<=sunday).length;
  const history=rows.map(x=>{const status=!x.secondary_observer_id?'No IOA observer':!x.secondary_record_id?'Waiting for IOA entry':ioaDisplay(x.ioa);return `<li><strong>${e(x.observation_date)} · ${e(x.phase)} observation #${x.session_number}</strong><br>Primary observer: ${e(x.primary_observer_code)}${x.secondary_observer_code?` · IOA observer: ${e(x.secondary_observer_code)}`:''}<br>Teacher fidelity: ${pct(x.teacher_fidelity_percent)} · Student target behavior: ${pct(x.student_target_behavior_percent)}<br>${e(status)} · Teacher IOA: ${pct(x.ioa?.teacher_fidelity_ioa_percent)} · Student IOA: ${pct(x.ioa?.student_behavior_ioa_percent)}<details><summary>View / Edit Data</summary>${recordForm(x,'primary',e)}${x.secondary_observer_id?recordForm(x,'secondary',e):''}</details></li>`;}).join('')||'<li>No classroom observations.</li>';
  const primaryOptions=observers.filter(x=>x.active&&(x.observer_type==='primary_researcher'||(x.observer_type==='trained_observer'&&x.status==='qualified')));
  return `<section id="operations-observations" class="panel observations-ioa operations-section"><p class="eyebrow">Observations</p><h2>Classroom Observations &amp; IOA</h2><nav class="subnav">New Observation · Observation Setup · Observation History · IOA Summary</nav><div class="observation-stats"><div><span>Completed</span><strong>${coverage.completed||0}</strong></div><div><span>IOA Coverage</span><strong>${pct(coverage.percent||0)}</strong><small>${coverage.ioa||0} paired · minimum ${coverage.required_minimum||0} · ${coverage.additional_needed||0} additional needed</small></div><div><span>Baseline</span><strong>${baseline} / ${item.protocol?.planned_baseline_observations||'not assigned'}</strong></div><div><span>Maintenance</span><strong>${maintenance}</strong><small>Expected: 2–3 over approximately 3–5 weeks</small></div>${item.current_phase==='intervention'?`<div><span>This Week</span><strong>${weekCount}</strong><small>Goal: about 3 observations/week</small></div>`:''}</div>${baseline>=(item.protocol?.planned_baseline_observations||Infinity)?'<p class="ready">Baseline minimum observation count met</p><p class="needs">Researcher phase decision required</p>':''}<form id="observation-setup-form" class="compact-form"><h3>Observation Setup</h3><label>Routine<input name="routine" maxlength="1000" value="${e(setup?.target_routine||'')}" required></label><label>Target behavior definition<textarea name="definition" maxlength="2000" required>${e(setup?.target_behavior_definition||'')}</textarea></label><label>Change note — optional<input name="change_note" maxlength="1000"></label><button class="primary">Save Observation Setup</button></form><form id="new-observation-form" class="compact-form"><h3>New Observation</h3><label>Date<input name="date" type="date" required></label><label>Start time — optional<input name="start" type="time"></label><label>End time — optional<input name="end" type="time"></label><label>Primary observer<select name="primary" required><option value="">Select</option>${primaryOptions.map(x=>`<option value="${x.id}">${e(x.observer_code)}</option>`).join('')}</select></label><label>IOA observer — optional<select name="secondary"><option value="">No IOA observer</option>${observers.filter(x=>x.active&&x.observer_type==='trained_observer'&&x.status==='qualified').map(x=>`<option value="${x.id}">${e(x.observer_code)}</option>`).join('')}</select></label><label>Note — optional<textarea name="note" maxlength="1000"></textarea></label><p>Phase is pulled from the case record for this date.</p><button class="primary">Save Observation</button></form><h3>Observation History</h3><ol class="observation-history">${history}</ol><h3>IOA Summary</h3><p>Coverage target: at least 20% across phases and dyads. Ongoing agreement must be <strong>&gt;80%</strong>; exactly 80% requires recalibration. Not-calculable IOA requires review but does not automatically require recalibration.</p></section>`;
}

export function recordPayload(form){const fidelity=[...form.querySelectorAll('.fidelity-entry fieldset')].map(x=>({target_key:x.dataset.target,status:x.querySelector('input:checked')?.value})),intervals=[...form.querySelectorAll('.interval-cell')].map(x=>({interval_number:Number(x.dataset.interval),status:x.dataset.status}));return{fidelity,intervals};}
export function cycleInterval(button){const next={no_occurrence:'occurrence',occurrence:'not_observed',not_observed:'no_occurrence'}[button.dataset.status];button.dataset.status=next;button.textContent=next==='occurrence'?'X':next==='not_observed'?'O':'\u00a0';}
export function updatePreviews(form){const {fidelity,intervals}=recordPayload(form),f=fidelitySummary(fidelity),i=intervalSummary(intervals);form.querySelector('.fidelity-preview').textContent=`Implemented: ${f.implemented} · Not Implemented: ${f.notImplemented} · No Opportunity: ${f.noOpportunity} · Fidelity: ${pct(f.percent)}`;form.querySelector('.interval-preview').textContent=`X intervals: ${i.occurrence} · O intervals: ${i.notObserved} · Observed intervals: ${i.observed} · Target behavior: ${pct(i.percent)}`;}
