import assert from 'node:assert/strict';
import fs from 'node:fs';
import { CHECKLIST, MEASURES, PHASES, COACHING_FOCUSES, LIFECYCLE_STAGES, baselineReadiness, gameReadiness, gamePreparationReadiness, measureNeeds, interventionReadiness, attentionForCase, studyWideAttention, timelineForCase, checklistStatuses, denverToday, lifecycleStage, nextAction, observationSummary, interventionElapsed } from './operations-model.mjs';
import { renderOperations } from './operations-ui.mjs';
import { renderGameCreation } from './game-creation-ui.mjs';
const sql=fs.readFileSync(new URL('../supabase/migrations/20260818060000_research_operations_foundation.sql',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('admin.js',import.meta.url),'utf8');
const ui=fs.readFileSync(new URL('operations-ui.mjs',import.meta.url),'utf8');
const gameUi=fs.readFileSync(new URL('game-creation-ui.mjs',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('admin.css',import.meta.url),'utf8');
const readyFixture=()=>({current_phase:'prebaseline',study_id:'CASE-TEST',student_alias:'Student',case_active:false,participant_active:false,protocol:{stagger_position:1,planned_baseline_observations:6},checklist:[],measures:[],tasks:[],study_events:[],coaching_contacts:[],phase_history:[]});
assert.deepEqual(PHASES,['prebaseline','baseline','intervention','maintenance','complete','withdrawn']);
assert.deepEqual(MEASURES.map(x=>x[0]),['tses_pre','tses_post','urp_ir','teacher_interview']);
assert.deepEqual(CHECKLIST.map(x=>x[0]),['teacher_consent','parent_permission','student_assent','bsp_technical_review','safety_screen','target_routine_finalized','target_behavior_definition','fidelity_checklist_finalized','fidelity_checklist_second_review','baseline_orientation','intervention_orientation']);
assert.deepEqual(COACHING_FOCUSES,['observation','consultation','performance_feedback','modeling','data_review','problem_solving','responsive_support','other']);
assert.deepEqual(checklistStatuses('student_assent'),['pending','complete','not_applicable']);
for(const [key] of CHECKLIST.filter(([key])=>key!=='student_assent')) assert.deepEqual(checklistStatuses(key),['pending','complete'],key);
assert.equal(denverToday(new Date('2026-08-19T05:30:00Z')),'2026-08-18');
for(const table of ['research_case_protocol','research_case_protocol_events','research_protocol_checklist_events','research_case_phase_events','research_tasks','research_measure_events','research_coaching_contacts','research_study_events']) assert.match(sql,new RegExp(`create table public\\.${table}`));
for(const pair of ['when 1 then 6','when 2 then 8','when 3 then 10','when 4 then 12','when 5 then 14']) assert.match(sql,new RegExp(pair));
assert.match(sql,/constraint research_case_protocol_stagger_position_key unique\(stagger_position\) deferrable/);
assert.match(sql,/baseline prerequisites missing/);assert.match(sql,/student_assent[\s\S]*not in \('complete','not_applicable'\)/);
assert.match(sql,/status_date date not null/);assert.match(sql,/recorded_at timestamptz not null default now/);
assert.match(sql,/checklist status date is required/);assert.match(sql,/checklist status date cannot be in the future \(America\/Denver\)/);
assert.match(sql,/coaching contact date cannot be in the future \(America\/Denver\)/);assert.match(sql,/study event date cannot be in the future \(America\/Denver\)/);
const taskRpc=sql.slice(sql.indexOf('create function public.research_admin_create_task'),sql.indexOf('create function public.research_admin_set_task_status'));assert.doesNotMatch(taskRpc,/future|denver_today|America\/Denver/);
assert.match(sql,/completion date is required when measure status is complete/);assert.match(sql,/measure completion date cannot be in the future \(America\/Denver\)/);
assert.match(sql,/status='complete' and completed_on is not null/);assert.match(sql,/status<>'complete' and completed_on is null/);
assert.match(sql,/target_external_reference/);assert.match(sql,/target_brief_note/);assert.match(sql,/prepared_content/);
assert.doesNotMatch(sql,/update public\.(cases|participants|teacher_reminder_settings)/i);assert.doesNotMatch(sql,/resend|send_email|net\.http|cron/i);
assert.match(sql,/enable row level security/);assert.match(sql,/public\.is_research_admin\(\)/);assert.match(sql,/prevent_research_operations_delete/);
assert.match(html,/Study Overview/);assert.match(html,/Intake Queue/);assert.match(html,/id="study-wide-tasks"/);
assert.match(ui,/Study Tasks/);assert.match(js,/target_case_id:caseId/);assert.match(js,/target_required:f\.has\('required'\)/);assert.match(js,/target_note:f\.get\('note'\)/);
assert.match(ui,/data-status="not_applicable"/);assert.match(ui,/Required\?/);assert.match(ui,/Note — optional/);
assert.match(ui,/class="checklist-card checklist-form"/);assert.match(ui,/maxlength="1000"[\s\S]*Note/);assert.match(ui,/name="status_date" type="date" required/);
assert.match(css,/\.baseline-checklist-grid\s*\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(css,/@media\(max-width:800px\)\{\.baseline-checklist-grid\{grid-template-columns:1fr\}\}/);
const checklistRpc="operationRpc('research_admin_record_checklist_status',{target_case_id:caseId,target_item_key:form.dataset.key,target_status:f.get('status'),target_status_date:f.get('status_date'),target_brief_note:f.get('note')||null})";
assert.ok(js.includes(checklistRpc));
const renderedOperations=renderOperations(readyFixture(),{},x=>String(x));
const qualtricsUrl='https://x.qualtrics.com/jfe/form/SV_example?participant_code=MR-001';
const configuredOperations=renderOperations(readyFixture(),{},x=>String(x),{qualtricsMeasures:{tses_pre:{configured:true,url:qualtricsUrl},tses_post:{configured:true,url:qualtricsUrl},urp_ir:{configured:true,url:qualtricsUrl},teacher_interview:{configured:true,url:'https://x.qualtrics.com/jfe/form/SV_interview'}}});
for(const label of ['Open TSES Pre','Open TSES Post','Open URP-IR','Open Interview Record'])assert.match(configuredOperations,new RegExp(label));
assert.equal((configuredOperations.match(/Copy Teacher Link/g)||[]).length,3);
assert.match(configuredOperations,/Researcher-entered form\. Enter the participant Study ID at the top\./);
assert.equal((configuredOperations.match(/class="inline-record measure-form"/g)||[]).length,4,'all existing manual measure forms remain');
assert.match(renderedOperations,/TSES Pre Qualtrics survey not configured/);
assert.match(js,/copy-qualtrics-link[\s\S]*navigator\.clipboard/);
assert.match(js,/window\.prompt\('Copy teacher link:'/);
const copyBinding=js.slice(js.indexOf("document.querySelectorAll('.copy-qualtrics-link')"),js.indexOf(' bindObservationControls(caseId)'));
assert.doesNotMatch(copyBinding,/operationRpc|research_admin_record_measure|fetch\(/,'opening and copying have no record side effects');
const statusMarkup=renderOperations({...readyFixture(),study_day_status:{history:[
 {id:'current',study_date:'2026-08-24',reason:'teacher_unavailable',source:'daily_email',recorded_at:'2026-08-24T13:12:00Z'},
 {id:'old-teacher',study_date:'2026-08-23',reason:'teacher_absent',source:'daily_email',recorded_at:'2026-08-23T13:12:00Z'},
 {id:'old-student',study_date:'2026-08-22',reason:'student_absent',source:'daily_email',recorded_at:'2026-08-22T13:12:00Z'},
 {id:'old-schedule',study_date:'2026-08-21',reason:'schedule_disruption',source:'daily_email',recorded_at:'2026-08-21T13:12:00Z'}
],current:[{event_id:'current'}]}},{},x=>String(x));
assert.match(statusMarkup,/Teacher unavailable/);
for(const legacy of ['Teacher out (legacy)','Student out (legacy)','Schedule changed (legacy)'])assert.ok(statusMarkup.includes(legacy));
const correction=statusMarkup.match(/<form class="study-status-correction[\s\S]*?<\/form>/)[0];
assert.match(correction,/option value="teacher_unavailable">Teacher unavailable/);assert.match(correction,/option value="clear">Clear excuse/);
assert.doesNotMatch(correction,/option value="(?:teacher_absent|student_absent|schedule_disruption)"/);
const qaStatusMarkup=renderOperations({...readyFixture(),study_id:'MR-998'},{},x=>String(x));
assert.match(qaStatusMarkup,/Generate today’s QA status link/);assert.doesNotMatch(qaStatusMarkup,/Generate today’s QA status links/);
const authoringWorkspace={case:{id:'case-1',case_code:'CASE-998',student_alias:'Star'},has_crisis_plan:false,fidelity_targets:[],missions:[]};
const renderedGameCreation=renderGameCreation(authoringWorkspace,null,null);
assert.match(renderedGameCreation,/Author mission drafts/);
for(const heading of ['GAME SETUP','BIP Briefing','MISSION BANK','Daily Missions','Mystery Missions','Crisis Missions','Resource Map','BIP at a Glance','Fidelity Fortress']) assert.match(renderedGameCreation,new RegExp(heading));
assert.match(renderedGameCreation,/Legacy local build instructions remain available in documentation during the transition/);
assert.doesNotMatch(renderedGameCreation,/Terminal|create-private-case-starter|protected-seed|Publish Game/);
assert.match(js,/research_admin_game_authoring_workspace/);
assert.match(js,/research_admin_save_mission_draft/);
assert.doesNotMatch(renderedGameCreation,/Create Test Login Link|Send Game Login/);
assert.match(renderedGameCreation,/data-key="intervention_orientation"/);
const gameReady=renderedOperations.slice(renderedOperations.indexOf('id="operations-game-ready"'),renderedOperations.indexOf('id="operations-intervention"'));
for (const label of ['Protected game content','Resource Map','Behavior Review','Privacy Review','QA Preview','Teacher account','MR intervention orientation']) assert.match(gameReady,new RegExp(label));
for (const forbidden of ['create-private-case-starter','Mission Authoring Standard','Supabase SQL Editor','preview-protected-game','signoff-action']) assert.doesNotMatch(gameReady,new RegExp(forbidden));
assert.match(gameReady,/id="open-game-creation"/);
const subnav=renderedOperations.slice(renderedOperations.indexOf('<nav class="operations-subnav"'),renderedOperations.indexOf('</nav>')+6);
assert.deepEqual([...subnav.matchAll(/<a href="([^"]+)">([^<]+)<\/a>/g)].map(([,href,label])=>[label,href]),[['Overview','#operations-overview'],['Phase Decision','#operations-phase-decision'],['Enrollment','#operations-enrollment'],['Prebaseline','#operations-prebaseline'],['Baseline','#operations-baseline'],['Game Ready','#operations-game-ready'],['Intervention','#operations-intervention'],['Study-day Context','#operations-study-day-context'],['End Measures','#operations-end-measures'],['Maintenance','#operations-maintenance'],['Closeout','#operations-closeout'],['Events','#operations-events'],['History','#operations-history']]);
assert.deepEqual(LIFECYCLE_STAGES,['Enrollment','Prebaseline','Baseline','Game Ready','Intervention','End Measures','Maintenance','Closeout']);
let previous=-1; for(const stage of LIFECYCLE_STAGES){const at=renderedOperations.indexOf(`>${stage}</li>`);assert.ok(at>previous,stage);previous=at;}
assert.match(renderedOperations,/lifecycle-current" aria-current="step"[^>]*><span>1<\/span>Enrollment/);
const enrollment=renderedOperations.slice(renderedOperations.indexOf('id="operations-enrollment"'),renderedOperations.indexOf('id="operations-prebaseline"'));
let permissionOrder=-1; for(const key of ['teacher_consent','parent_permission','student_assent']){const at=enrollment.indexOf(`data-key="${key}"`);assert.ok(at>permissionOrder,key);permissionOrder=at;}
const tsesAt=enrollment.indexOf('data-key="tses_pre"');
assert.ok(tsesAt>permissionOrder,'TSES follows formal permissions');
assert.ok(enrollment.indexOf('<h3>Pre-Baseline TSES</h3>')>permissionOrder);
assert.ok(enrollment.indexOf('<h3>Early Prep</h3>')>tsesAt,'TSES precedes Early Prep');
assert.ok(enrollment.indexOf('data-key="bsp_technical_review"')>tsesAt);
for(const [key] of CHECKLIST) assert.match(renderedOperations+renderedGameCreation,new RegExp(`data-key="${key}"`));
assert.match(renderedOperations,/data-key="student_assent"[\s\S]*option value="not_applicable"/);
assert.match(enrollment,/Research data collection still waits for required permissions/);
assert.doesNotMatch(renderedOperations,/operations-observations|>Observations<|record-observation-form/);
assert.match(renderedOperations,/Baseline assignment is locked once baseline begins|Baseline assignment/);
assert.ok(renderedOperations.indexOf('TSES — Post-Intervention')<renderedOperations.indexOf('id="operations-maintenance"'));
assert.ok(renderedOperations.indexOf('id="operations-phase-decision"')>renderedOperations.indexOf('id="operations-overview"'));assert.ok(renderedOperations.indexOf('id="operations-phase-decision"')<renderedOperations.indexOf('id="operations-enrollment"'));
assert.doesNotMatch(renderedOperations,/Make a deliberate researcher decision|Research Admin never changes phases automatically\./);assert.match(renderedOperations,/Phase Decision[\s\S]*Record Phase Change[\s\S]*Phase History/);
assert.match(renderedOperations,/Case History[\s\S]*append-only history/);
assert.match(ui,/class="inline-record measure-form"/);assert.match(ui,/external_reference/);assert.match(js,/Completion date is required/);
const prebaseline=renderedOperations.slice(renderedOperations.indexOf('id="operations-prebaseline"'),renderedOperations.indexOf('id="operations-baseline"'));
assert.doesNotMatch(prebaseline,/TSES — Pre-Baseline|data-key="tses_pre"/,'Prebaseline does not duplicate the TSES record');
assert.equal((renderedOperations.match(/class="inline-record measure-form" data-key="tses_pre"/g)||[]).length,1,'Research Operations renders one tses_pre form');
assert.doesNotMatch(renderedOperations,/Go to TSES|id="go-to-tses"|id="baseline-tses-status"/);
assert.doesNotMatch(js,/go-to-tses/);
assert.match(js,/research_admin_record_measure[\s\S]*target_measure_key:form\.dataset\.key/,'existing measure submit handler records tses_pre by its form data key');
const completedTsesMarkup=renderOperations({...readyFixture(),measures:[{measure_key:'tses_pre',status:'complete',completed_on:'2026-08-20',external_reference:'TSES-20',brief_note:'Recorded'}]}, {}, x=>String(x));
const completedEnrollment=completedTsesMarkup.slice(completedTsesMarkup.indexOf('id="operations-enrollment"'),completedTsesMarkup.indexOf('id="operations-prebaseline"'));
assert.match(completedEnrollment,/data-key="tses_pre"[\s\S]*option value="complete" selected[\s\S]*value="2026-08-20"[\s\S]*value="TSES-20"[\s\S]*value="Recorded"/,'saved TSES values remain visible in Enrollment');
const measureSubmit=js.slice(js.indexOf("document.querySelectorAll('.measure-form')"),js.indexOf("$('#phase-form')"));
assert.doesNotMatch(measureSubmit,/research_admin_record_phase|target_phase/,'saving a measure does not change phase automatically');
for(const field of ['affects_observation','affects_mr_exposure','affects_phase_interpretation','action_taken']){assert.match(ui,new RegExp(field));assert.match(js,new RegExp(field));}
assert.match(js,/research_admin_resolve_study_event[\s\S]*target_action_taken:action/);
assert.match(ui,/Duration — optional/);assert.match(js,/target_approximate_duration_minutes/);assert.match(ui,/name="focus"/);assert.match(js,/COACHING_FOCUSES\.includes/);
const completeChecklist=CHECKLIST.map(([item_key])=>({item_key,status:'complete'}));
const ready={current_phase:'prebaseline',protocol:{stagger_position:1},checklist:completeChecklist,measures:[{measure_key:'tses_pre',status:'complete'}],tasks:[],study_events:[]};
assert.equal(baselineReadiness(ready).ready,true);assert.equal(baselineReadiness({...ready,protocol:null}).ready,false);
for(const [key] of CHECKLIST.slice(0,10)){const item={...ready,checklist:completeChecklist.filter(x=>x.item_key!==key)};assert.equal(baselineReadiness(item).ready,false,key);}
assert.equal(baselineReadiness({...ready,checklist:completeChecklist.map(x=>x.item_key==='student_assent'?{...x,status:'not_applicable'}:x)}).ready,true);
assert.equal(baselineReadiness({...ready,measures:[]}).ready,false);
assert.deepEqual(measureNeeds({...ready,current_phase:'maintenance'}),['tses_post','urp_ir','teacher_interview']);
assert.equal(studyWideAttention([{title:'IRB follow-up',status:'pending',due_date:'2026-01-01'}],'2026-01-02')[0],'Study task overdue: IRB follow-up');
const intervention={...ready,current_phase:'intervention',case_active:false,participant_active:false,prepared_content:{protected_content_present:false,resource_map_ready:false,reminders_enabled:false},checklist:completeChecklist.filter(x=>x.item_key!=='intervention_orientation')};
assert.deepEqual(interventionReadiness(intervention).missing,['MR intervention orientation','Game content','Resource Map','Game turned on','Reminders turned on']);
assert.equal(attentionForCase(intervention).filter(x=>x.endsWith('needed for intervention')).length,5);
const withoutComparability={...ready,prepared_content:{protected_content_present:true,resource_map_ready:true},checklist:completeChecklist};
assert.equal(gameReadiness(withoutComparability).ready,true,'game readiness does not require comparability');
const preparedForLaunch={protected_content:{present:true,version:4},resource_map:{status:'Ready',behavior_reviewed:true,privacy_reviewed:true,qa_previewed:true},teacher_account_ready:true,reminders:{enabled:false}};
const launchReady={...withoutComparability,case_active:false,participant_active:false};
assert.equal(gamePreparationReadiness(launchReady,preparedForLaunch).ready,true,'pre-launch readiness does not require access or reminders');
const versionedMarkup=renderGameCreation(authoringWorkspace,null,null);
assert.doesNotMatch(versionedMarkup,/protected-content version|data-review-type|Mission Review|Comparability/);

assert.equal(interventionReadiness({...withoutComparability,current_phase:'intervention',case_active:true,participant_active:true,prepared_content:{...withoutComparability.prepared_content,reminders_enabled:true}}).ready,true,'intervention readiness does not require comparability');
const timeline=timelineForCase({checklist_history:[{item_key:'teacher_consent',status:'complete',status_date:'2026-01-03',recorded_at:'2026-01-01'}],phase_history:[{phase:'baseline',effective_date:'2026-01-02'}]});assert.equal(timeline[0].category,'Protocol');assert.equal(timeline[0].date,'2026-01-03');assert.equal(timeline[0].label,'Teacher consent — Complete');
assert.equal(lifecycleStage(readyFixture()),'Enrollment');
assert.equal(lifecycleStage(ready),'Prebaseline');
assert.equal(nextAction({...ready,measures:[]}), 'Complete the pre-baseline TSES.');
const baselineRows=[1,2,3,4,5,6].map(session_number=>({id:`o${session_number}`,phase:'baseline',session_number,summary_revision_id:`r${session_number}`,observation_date:`2026-08-${String(session_number).padStart(2,'0')}`,teacher_fidelity_percent:80+session_number,student_target_behavior_percent:20,}));
const baselineCase={...ready,current_phase:'baseline',protocol:{stagger_position:1,planned_baseline_observations:6},prepared_content:{protected_content_present:false,resource_map_ready:false},observation_data:{observations:[...baselineRows,{id:'o7',phase:'baseline',session_number:7,observation_date:'2026-08-07',}],coverage:{percent:20}}};
assert.equal(observationSummary(baselineCase).baseline,6,'baseline count uses finalized direct-observation records');
assert.equal(lifecycleStage(baselineCase),'Game Ready');
assert.equal(nextAction(baselineCase),'Finish game readiness before starting intervention.');
const highFidelityRows=[1,2,3].map(session_number=>({id:`i${session_number}`,phase:'intervention',session_number,summary_revision_id:`ir${session_number}`,observation_date:`2026-08-${10+session_number}`,teacher_fidelity_percent:92,student_target_behavior_percent:20,}));
const interventionCase={...baselineCase,current_phase:'intervention',phase_history:[{phase:'intervention',effective_date:'2026-08-01'}],observation_data:{...baselineCase.observation_data,observations:highFidelityRows}};
assert.deepEqual(interventionElapsed(interventionCase,new Date('2026-08-20T05:00:00Z')),{effectiveDate:'2026-08-01',days:18,weeks:18/7,minimumMet:false},'elapsed dates use the America/Denver calendar day');
const beforeMinimum=nextAction(interventionCase,new Date('2026-08-20T05:00:00Z'));
assert.equal(beforeMinimum,'Fidelity criterion is met. Continue intervention until the 4-week minimum, then review the data for a phase decision.');
assert.doesNotMatch(beforeMinimum,/criteria may be met/i);
const afterMinimum=nextAction(interventionCase,new Date('2026-08-29T18:00:00Z'));
assert.equal(afterMinimum,'Objective intervention criteria are met. Review trend and make the researcher phase decision.');
assert.doesNotMatch(afterMinimum,/downward trend (?:met|passed|satisfied)/i);
assert.match(nextAction({...interventionCase,phase_history:[]},new Date('2026-09-20T18:00:00Z')),/Confirm intervention timing/);
const interventionMarkup=renderOperations(interventionCase, {reminders:{enabled:false}}, x=>String(x));
assert.doesNotMatch(interventionMarkup,/game score[^<]*(meets|pass|criterion met)/i);
assert.match(interventionMarkup,/Game score is never a criterion/);
assert.match(interventionMarkup,/Elapsed intervention time[\s\S]*days · ~[\s\S]*weeks/);
assert.match(interventionMarkup,/no clear downward trend[\s\S]*Researcher phase decision required/);
assert.doesNotMatch(interventionMarkup,/Current probes/);
const baselineMarkup=renderOperations(baselineCase,{reminders:{enabled:false}},x=>String(x));
const baselineIntervention=baselineMarkup.slice(baselineMarkup.indexOf('id="operations-intervention"'),baselineMarkup.indexOf('id="operations-end-measures"'));
assert.match(baselineIntervention,/Not started\.[\s\S]*Game access:[\s\S]*Reminders:[\s\S]*View Intervention Details/);
assert.match(baselineIntervention,/<details><summary>View Intervention Details<\/summary>/,'future intervention details are collapsed by default');
assert.doesNotMatch(baselineIntervention,/<details open/);
const activeIntervention=interventionMarkup.slice(interventionMarkup.indexOf('id="operations-intervention"'),interventionMarkup.indexOf('id="operations-end-measures"'));
assert.match(activeIntervention,/Intervention Status[\s\S]*This Week[\s\S]*INTERVENTION_FIDELITY/);
assert.doesNotMatch(activeIntervention,/View Intervention Details/);
const baselineEnd=baselineMarkup.slice(baselineMarkup.indexOf('id="operations-end-measures"'),baselineMarkup.indexOf('id="operations-maintenance"'));
assert.match(baselineEnd,/Complete after intervention\.[\s\S]*View Details/);
assert.match(baselineEnd,/<details><summary>View Details<\/summary>/);
const interventionEnd=interventionMarkup.slice(interventionMarkup.indexOf('id="operations-end-measures"'),interventionMarkup.indexOf('id="operations-maintenance"'));
assert.match(interventionEnd,/Complete after intervention\./);
const baselineMaintenance=baselineMarkup.slice(baselineMarkup.indexOf('id="operations-maintenance"'),baselineMarkup.indexOf('id="operations-closeout"'));
assert.match(baselineMaintenance,/Begins after Mission: Reinforceable is withdrawn\.[\s\S]*Target: 2–3 observations across approximately 3–5 weeks\./);
const baselineCloseout=baselineMarkup.slice(baselineMarkup.indexOf('id="operations-closeout"'),baselineMarkup.indexOf('id="operations-events"'));
assert.match(baselineCloseout,/Available after maintenance\.[\s\S]*View Closeout Details/);
assert.match(baselineMarkup,/id="operations-baseline"[\s\S]*Record Baseline Observation[\s\S]*Baseline Observation History/);
assert.match(interventionMarkup,/id="operations-intervention"[\s\S]*Record Intervention Observation[\s\S]*Intervention Observation History/);
const maintenanceMarkup=renderOperations({...baselineCase,current_phase:'maintenance',case_active:true,participant_active:true}, {reminders:{enabled:true}}, x=>String(x));
assert.match(maintenanceMarkup,/Maintenance is active, but game access is still On/);
assert.match(maintenanceMarkup,/Maintenance is active, but reminders are still On/);
const maintenanceSection=maintenanceMarkup.slice(maintenanceMarkup.indexOf('id="operations-maintenance"'),maintenanceMarkup.indexOf('id="operations-closeout"'));
assert.match(maintenanceSection,/Maintenance Status[\s\S]*Completed probes[\s\S]*Record Maintenance Observation[\s\S]*Maintenance Observation History/);
assert.doesNotMatch(maintenanceSection,/View Maintenance Details/);
const maintenanceEnd=maintenanceMarkup.slice(maintenanceMarkup.indexOf('id="operations-end-measures"'),maintenanceMarkup.indexOf('id="operations-maintenance"'));
assert.match(maintenanceEnd,/class="inline-record measure-form"/,'full end-measure controls render after intervention');
assert.doesNotMatch(maintenanceMarkup,/id="operations-observations"/);
const postMeasures=['tses_post','urp_ir','teacher_interview'].map(measure_key=>({measure_key,status:'complete'}));
const maintenanceRows=[1,2].map(session_number=>({id:`m${session_number}`,phase:'maintenance',session_number,summary_revision_id:`mr${session_number}`,observation_date:`2026-09-0${session_number}`,}));
const maintenanceNext=nextAction({...baselineCase,current_phase:'maintenance',measures:[...baselineCase.measures,...postMeasures],observation_data:{...baselineCase.observation_data,observations:maintenanceRows}});
assert.equal(maintenanceNext,'Maintenance target range met. Decide whether one more probe is needed.');
assert.doesNotMatch(maintenanceNext,/3 of 3|third.*required/i);
console.log('Research operations hardening, forms, readiness, attention, security, and timeline checks passed.');
