import { CHECKLIST, MEASURES, PHASES, COACHING_FOCUSES, TASK_CATEGORIES, currentByKey, baselineReadiness, attentionForCase, timelineForCase, denverToday, checklistStatuses, LIFECYCLE_STAGES, lifecycleStage, nextAction, observationSummary, gamePreparationReadiness, interventionElapsed } from './operations-model.mjs';
import { renderObservationSetup, renderPhaseObservationWorkspace } from './observations-ui.mjs';

export function renderWeeklyCheckins(item,e){
 const rows=item.weekly_checkins||[], configured=item.weekly_qualtrics_configured;
 const list=rows.length?rows.map(row=>`<li><strong>Week of ${e(row.week_start)}–${e(row.week_end)}</strong><br>Expected · ${row.link_issued_at?'Link issued':'Link not issued'} · ${row.completed_at?`Complete · ${e(new Date(row.completed_at).toLocaleString())}`:e(row.status==='upcoming'?'Upcoming':'Not complete')}</li>`).join(''):'<li>No Intervention weeks expected yet.</li>';
 const qa='';
 return `<details class="weekly-checkins"><summary>Weekly Teacher Report history</summary><p>Qualtrics survey: <strong class="${configured?'ready':'needs'}">${configured?'Configured':'Not configured'}</strong></p><ol>${list}</ol>${qa}</details>`;
}
export const privacy='<small class="privacy-help">Keep notes brief. Do not include student names, diagnoses, or protected BIP/BSP content.</small>';
const opts=(values,current)=>values.map(v=>`<option value="${v}" ${v===current?'selected':''}>${v.replaceAll('_',' ')}</option>`).join('');
export function taskList(tasks,e){return (tasks||[]).map(t=>`<li class="${t.overdue?'high-attention':''}"><strong>${e(t.title)}</strong> · ${e(t.status)}${t.required?' · Required':''}${t.due_date?` · due ${e(t.due_date)}`:''}${t.note?`<br><span>${e(t.note)}</span>`:''}<span class="row-actions">${t.status==='pending'?`<button class="quiet task-action" data-id="${t.id}" data-status="complete">Complete</button><button class="quiet task-action" data-id="${t.id}" data-status="not_applicable">Mark N/A</button>`:`<button class="quiet task-action" data-id="${t.id}" data-status="pending">Reopen</button>`}</span></li>`).join('')||'<li>No tasks recorded.</li>';}
export function taskForm(id,heading='Add Task'){return `<form id="${id}" class="compact-form"><h3>${heading}</h3><label>Title<input name="title" maxlength="160" required></label><label>Category<select name="category">${opts(TASK_CATEGORIES)}</select></label><label>Due date — optional<input name="due_date" type="date"></label><label class="check-option"><input name="required" type="checkbox"> Required?</label><label>Note — optional<textarea name="note" maxlength="1000"></textarea></label>${privacy}<button class="primary">Add Task</button></form>`;}
export function renderStudyWideTasks(tasks,e){return `<section class="panel study-wide-tasks"><p class="eyebrow">Tasks</p><h2>Study Tasks</h2>${taskForm('study-task-form')}<ul>${taskList(tasks,e)}</ul></section>`;}
export function renderOperations(item,prepared,e,launchConfig={}){
 if(!item)return '';
 const checklist=currentByKey(item.checklist),measures=currentByKey(item.measures,'measure_key'),baseline=baselineReadiness(item),timeline=timelineForCase(item),stage=lifecycleStage(item),stats=observationSummary(item),game=gamePreparationReadiness(item,prepared),elapsed=interventionElapsed(item);
 const gameOn=Boolean(item.case_active&&item.participant_active),remindersOn=Boolean(prepared.reminders?.enabled),phase=item.current_phase||'prebaseline';
 const pct=value=>value===null||value===undefined?'—':`${Number(value).toFixed(1)}%`;
 const checklistCard=([key,label])=>{const row=checklist[key]||{},statuses=checklistStatuses(key);return `<form class="checklist-card checklist-form" data-key="${key}"><strong class="checklist-card-label">${e(label)}</strong><div class="checklist-card-controls"><select name="status" aria-label="Status for ${e(label)}">${opts(statuses,row.status||'pending')}</select><input name="status_date" type="date" required value="${e(row.status_date||denverToday())}" aria-label="Status date for ${e(label)}"></div><input class="checklist-card-note" name="note" maxlength="1000" value="${e(row.brief_note||'')}" aria-label="Optional note for ${e(label)}" placeholder="Note"><button class="quiet checklist-card-save">Save</button></form>`};
 const measureForm=([key,label])=>{const row=measures[key]||{};return `<form class="inline-record measure-form" data-key="${key}"><strong>${e(label)}</strong><select name="status">${opts(['pending','complete','declined','not_applicable'],row.status||'pending')}</select><input name="completed_on" type="date" value="${e(row.completed_on||'')}" aria-label="Completed date"><input name="external_reference" maxlength="250" value="${e(row.external_reference||'')}" placeholder="Response ID / reference"><input name="note" maxlength="1000" value="${e(row.brief_note||'')}" placeholder="Note"><button class="quiet">Save</button></form>`};
 const formal=CHECKLIST.slice(0,3).map(checklistCard).join(''),prep=CHECKLIST.slice(3,9).map(checklistCard).join(''),orientation=CHECKLIST.slice(9,10).map(checklistCard).join('');
 const baselineLocked=['baseline','intervention','maintenance','complete','withdrawn'].includes(phase),assignment=item.protocol?`Position ${e(item.protocol.stagger_position)} · ${e(item.protocol.planned_baseline_observations)} observations`:'Not assigned';
 const protocolControl=baselineLocked?`<div class="baseline-assignment"><strong>Baseline assignment</strong><p>${assignment}</p></div>`:`<form id="protocol-form" class="compact-form"><label>Baseline assignment<input name="position" type="number" min="1" max="5" value="${item.protocol?.stagger_position||''}" required></label><small>1 = 6 observations · 2 = 8 · 3 = 10 · 4 = 12 · 5 = 14</small><button class="primary">Save Baseline Assignment</button></form>`;
 const qualtrics=launchConfig.qualtricsMeasures||{};
 const surveyAction=(key,openLabel,{copy=true,note='Qualtrics will receive the coded Study ID automatically.',missing}={})=>{const measure=qualtrics[key];if(!measure?.configured||!measure.url)return `<div class="qualtrics-action"><p class="needs">${e(missing||`${openLabel} Qualtrics survey not configured`)}</p></div>`;return `<div class="qualtrics-action no-print"><a class="quiet" href="${e(measure.url)}" target="_blank" rel="noopener noreferrer">${e(openLabel)}</a>${copy?`<button class="quiet copy-qualtrics-link" data-url="${e(measure.url)}" type="button">Copy Teacher Link</button>`:''}<p class="neutral-note">${e(note)}</p><p class="copy-qualtrics-feedback message" role="status"></p></div>`;};
 const tsesRecording=`<h3>Pre-Baseline TSES</h3><p>Record the teacher's pre-baseline TSES here.</p>${surveyAction('tses_pre','Open TSES Pre',{missing:'TSES Pre Qualtrics survey not configured'})}<div class="inline-record-list">${measureForm(MEASURES.find(([key])=>key==='tses_pre'))}</div>`;
 const lifecycle=LIFECYCLE_STAGES.map((name,index)=>{const current=LIFECYCLE_STAGES.indexOf(stage),state=index<current?'complete':index===current?'current':'future';return `<li class="lifecycle-${state}" ${state==='current'?'aria-current="step"':''}><span>${index+1}</span>${name}</li>`}).join('');
 const eventRows=(item.study_events||[]).map(x=>`<li class="${['safety_concern','protocol_deviation'].includes(x.event_type)&&!x.resolved_at?'high-attention':''}"><strong>${e(x.event_type.replaceAll('_',' '))}</strong> · ${e(x.event_date)} · ${x.resolved_at?'Resolved':`Unresolved <button class="quiet resolve-event" data-id="${x.id}">Resolve</button>`}${x.action_taken?`<br>Action: ${e(x.action_taken)}`:''}</li>`).join('')||'<li>No study events.</li>';
 const coaching=`<div class="coaching-work"><p><strong>Record coaching the teacher receives outside Mission: Reinforceable.</strong></p><form id="coaching-form" class="compact-form"><label>Date<input name="date" type="date" required></label><label>Format<select name="format">${opts(['in_person','virtual','email','phone','other'])}</select></label><label>Duration — optional<input name="duration" type="number" min="1" max="1440"></label><label>Provider<input name="provider" maxlength="160" required></label><fieldset><legend>Focus — choose at least one</legend><div class="choice-grid">${COACHING_FOCUSES.map(x=>`<label class="check-option"><input type="checkbox" name="focus" value="${x}"> ${x.replaceAll('_',' ')}</label>`).join('')}</div></fieldset><label>Note — optional<textarea name="note" maxlength="1000"></textarea></label>${privacy}<button class="primary">Save Coaching Contact</button></form><ol>${(item.coaching_contacts||[]).map(x=>`<li>${e(x.contact_date)} · ${e(x.format)} · ${e(x.provider_role)}${x.approximate_duration_minutes?` · ~${x.approximate_duration_minutes} minutes`:''} · ${e(x.focuses.join(', '))}</li>`).join('')||'<li>No contacts recorded.</li>'}</ol></div>`;
 const contentPresent=Boolean(prepared.protected_content?.present),resourceReady=prepared.resource_map?.status==='Ready',teacherReady=prepared.teacher_account_ready===true;
 const statusRow=(label,ready,readyText='Ready',needsText='Needs action')=>`<div class="launch-status-row"><span>${label}</span><strong class="${ready?'ready':'needs'}">${ready?readyText:needsText}</strong></div>`;
 const caseCode=item.case_code||item.study_id||'CASE CODE',phaseLabel=phase.replaceAll('_',' ');
 const statusContext=item.study_day_status||{history:[],current:[]},statusLabels={teacher_unavailable:'Teacher unavailable',teacher_absent:'Teacher out (legacy)',student_absent:'Student out (legacy)',schedule_disruption:'Schedule changed (legacy)'},currentIds=new Set((statusContext.current||[]).map(x=>x.event_id));
 const statusRows=(statusContext.history||[]).map(x=>`<li><strong>${e(x.study_date)}</strong> · ${e(statusLabels[x.reason]||'Excuse cleared')}${currentIds.has(x.id)?' <span class="pill">Current</span>':''}<br><small>Reported from ${x.source==='daily_email'?'daily email':'Research Admin'} · ${e(new Date(x.recorded_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}))}</small>${currentIds.has(x.id)?`<form class="study-status-correction compact-form" data-event-id="${e(x.id)}"><label>Correct status<select name="reason"><option value="teacher_unavailable">Teacher unavailable</option><option value="clear">Clear excuse</option></select></label><button class="quiet">Append correction</button></form>`:''}</li>`).join('');
 const isStatusQa=item.study_id==='MR-998'||['CASE-998','MR-998'].includes(caseCode);
 const adherence=statusContext.adherence||{};
 const adherenceSummary=statusContext.adherence_state==='intervention_not_started'?'<p class="neutral-note"><strong>Intervention not started</strong></p>':adherence.scheduledStudyDays===undefined?'':`<dl class="case-summary"><div><dt>Scheduled study days</dt><dd>${e(adherence.scheduledStudyDays)}</dd></div><div><dt>Excused</dt><dd>${e(adherence.excusedStudyDays)}</dd></div><div><dt>Expected mission days</dt><dd>${e(adherence.expectedMissionDays)}</dd></div><div><dt>Completed expected missions</dt><dd>${e(adherence.completedExpectedMissionDays)}</dd></div></dl>`;
 const studyDayContext=`<section id="operations-study-day-context" class="panel operations-section operations-stage-panel" data-operations-stage-panel="history" hidden><p class="eyebrow">Study-day context</p><h2>Teacher availability</h2><p class="neutral-note">Only a current teacher-unavailable status excuses a scheduled day from expected Mission: Reinforceable practice. This does not change phase, fidelity, observation, or other outcomes.</p>${adherenceSummary}${statusRows?`<ol>${statusRows}</ol>`:'<p>No study-day status has been reported.</p>'}${(statusContext.history||[]).length>1?`<details><summary>History / Audit (${statusContext.history.length} append-only records)</summary><p>Corrections retain every earlier report.</p></details>`:''}${isStatusQa?'<div class="no-print"><button id="generate-study-status-qa" class="quiet" type="button">Generate today’s QA status link</button><p id="study-status-qa-result" class="message"></p></div>':''}</section>`;
 const isLegacyDemo=/^CASE-DEMO-/.test(caseCode), emailReady=launchConfig.teacherReminderSystemEnabled===true, gameLoginReady=launchConfig.gameLoginEmailEnabled===true, loginStatus=launchConfig.gameLoginEmailStatus, draftChanged=launchConfig.unpublishedDraftChanges===true;
 const launchHeadline=phase==='intervention'?(gameOn?(remindersOn?'Intervention active':emailReady?'Game access active':'Game access active · email setup pending'):'Ready to launch'):(game.ready?'Published &amp; reviewed — waiting for intervention launch':'Game preparation in progress');
 const accessControl=gameOn?`<p class="ready">Teacher can now sign in to Mission: Reinforceable.</p><button id="deactivate-game-access" class="quiet" type="button">Deactivate Game Access</button>`:`<p>Teacher game is ready but still locked.</p><button id="activate-game-access" class="primary" type="button" ${phase!=='intervention'||!game.ready?'disabled':''}>Activate Game Access</button>${phase!=='intervention'?'<p class="neutral-note">Available after Intervention begins.</p>':''}`;
 const reminderControl=!emailReady?`<strong class="off">Not available yet</strong><p>Production email delivery has not been enabled.</p>`:remindersOn?`<strong class="ready">On</strong><button id="disable-daily-reminders" class="quiet" type="button">Disable Daily Reminders</button>`:`<strong>Off</strong><button id="enable-daily-reminders" class="primary" type="button" ${phase!=='intervention'||!gameOn?'disabled':''}>Enable Daily Reminders</button>`;
 const loginLabel=loginStatus?.outcome==='sent'?`<strong class="ready">Login email sent ${e(new Date(loginStatus.recorded_at).toLocaleString())}</strong>`:loginStatus?.outcome==='failed'?'<strong class="needs">Last send failed — retry available</strong>':!gameOn?`<strong>Available after Game Access is activated.</strong>${!gameLoginReady?'<p>Pending production email setup.</p>':''}`:!gameLoginReady?'<strong class="off">Pending production email setup.</strong>':'<strong class="ready">Ready to send</strong>';
 const loginControl=`${loginLabel}<button id="send-game-login" class="${loginStatus?.outcome==='sent'?'quiet':'primary'}" type="button" ${phase!=='intervention'||!gameOn||!game.ready||!gameLoginReady?'disabled':''}>${loginStatus?.outcome==='sent'?'Resend Login Email':'Send Game Login'}</button><p class="neutral-note">Sends password-setup instructions only. It does not change access, phase, publishing, or reminders.</p>`;
 const launchPanel=isLegacyDemo?'<div class="intervention-launch-state"><p class="neutral-note">Reserved demo access continues to use the existing demo workflow.</p></div>':`<div class="intervention-launch-state"><p class="eyebrow">INTERVENTION LAUNCH</p><h3>${launchHeadline}</h3>${statusRow('Current phase',true,e(phaseLabel),e(phaseLabel))}${statusRow('Game access',gameOn,'On','Off')}${statusRow('Daily reminders',remindersOn,'On','Off')}${phase!=='intervention'&&gameOn?'<p class="attention">Needs attention: game access is on outside Intervention.</p>':''}<p><strong>Teacher will receive published version v${e(prepared.protected_content?.version||'—')}.</strong><br>Unpublished draft changes are not included.${draftChanged?' Unpublished draft changes are currently present.':''}</p><section class="launch-step"><p class="eyebrow">STEP 1 — GAME ACCESS</p>${accessControl}<p class="neutral-note">This allows the teacher to sign in and play the current published version. It does not send an email or enable reminders.</p></section><section class="launch-step"><p class="eyebrow">STEP 2 — SEND GAME LOGIN</p>${loginControl}</section><section class="launch-step"><p class="eyebrow">STEP 3 — DAILY REMINDERS</p>${reminderControl}</section></div>`;
 const interventionFull=`${launchPanel}<section class="intervention-period-summary"><div class="section-heading"><div><p class="eyebrow">Intervention</p><h2>Intervention Period</h2></div><span class="phase-chip">${elapsed?`Week ${Math.floor(elapsed.days/7)+1}`:'Not started'}</span></div><div class="intervention-period-kpis"><div><span>Start</span><strong>${e(elapsed?.effectiveDate||'—')}</strong></div><div><span>Elapsed</span><strong>${elapsed?`${elapsed.days} days · ~${elapsed.weeks.toFixed(1)} weeks`:'—'}</strong></div><div><span>Game</span><strong>${gameOn?'On':'Off'}</strong></div><div><span>Daily reminders</span><strong>${remindersOn?'On':'Off'}</strong></div></div><p class="criterion-note"><strong>Maintenance eligibility:</strong> after the minimum intervention period, ≥90% teacher fidelity across 3 consecutive direct observations with no clear downward trend, followed by a researcher decision. Student behavior is informative, not a phase-change criterion.</p></section>${renderPhaseObservationWorkspace(item,'intervention',e)}<section class="intervention-support-tracking"><h3>Other Intervention Tracking</h3><div class="weekly-status"><span>Weekly Teacher Report automation: <strong class="${launchConfig.weeklyRecapSystemEnabled?'ready':'needs'}">${launchConfig.weeklyRecapSystemEnabled?'Enabled':'Disabled for QA'}</strong></span><span>Coaching-as-usual contacts: <strong>${(item.coaching_contacts||[]).length} case total</strong></span><span>Study events/issues: <strong>${(item.study_events||[]).filter(x=>!x.resolved_at).length} unresolved</strong></span></div>${renderWeeklyCheckins(item,e)}</section><!-- INTERVENTION_FIDELITY -->`;
 const endMeasure=(key,label,action)=>`<div class="external-measure">${action}<div class="inline-record-list">${measureForm([key,label])}</div></div>`;
 const endMeasuresFull=`<h2>Complete these after the final maintenance observation</h2>${endMeasure('tses_post','TSES — Post-Intervention',surveyAction('tses_post','Open TSES Post',{missing:'TSES Post Qualtrics survey not configured'}))}${endMeasure('urp_ir','URP-IR — Post-Intervention',surveyAction('urp_ir','Open URP-IR',{missing:'URP-IR Qualtrics survey not configured'}))}${endMeasure('teacher_interview','Teacher Interview — Post-Intervention',surveyAction('teacher_interview','Open Interview Record',{copy:false,note:'Researcher-entered form. Enter the participant Study ID at the top.',missing:'Teacher Interview Qualtrics survey not configured'}))}${privacy}`;
 const maintenanceFull=`<h2>Mission: Reinforceable Withdrawn</h2><p>Mission: Reinforceable access should be withdrawn and daily MR reminders should be off. Weekly Teacher Reports stop with Intervention.</p><p><strong>Post-intervention measures are administered after the final maintenance observation.</strong></p><p>Complete maintenance observations before administering post-intervention measures.</p>${phase==='maintenance'&&gameOn?'<p class="attention">Maintenance is active, but game access is still On.</p>':''}${phase==='maintenance'&&remindersOn?'<p class="attention">Maintenance is active, but reminders are still On.</p>':''}<h3>Maintenance Status</h3><div class="observation-stats"><div><span>Completed probes</span><strong>${stats.maintenance}</strong><small>Target: 2–3 over approximately 3–5 weeks</small></div><div><span>Latest teacher fidelity</span><strong>${pct(stats.latest?.teacher_fidelity_percent)}</strong></div><div><span>Latest student target behavior</span><strong>${pct(stats.latest?.student_target_behavior_percent)}</strong></div><div><span>IOA status</span><strong>${pct(stats.ioa.percent||0)}</strong></div></div>${renderPhaseObservationWorkspace(item,'maintenance',e)}`;
 const closeoutFull=`<h2>Confirm the case record is complete</h2><div class="readiness-summary"><span>Maintenance probes</span><strong>${stats.maintenance>=2?'Target met':`${stats.maintenance} of 2–3`}</strong><span>Post measures</span><strong>${['tses_post','urp_ir','teacher_interview'].every(key=>measures[key]?.status==='complete')?'Complete':'Still needed'}</strong><span>Unresolved study events</span><strong>${(item.study_events||[]).filter(x=>!x.resolved_at).length}</strong><span>Unresolved tasks</span><strong>${(item.tasks||[]).filter(x=>x.status==='pending').length}</strong><span>Outstanding IOA review</span><strong>${stats.reviewIssues}</strong><span>Case status</span><strong>${e(phase)}</strong></div><h3>Tasks</h3>${taskForm('task-form')}<ul>${taskList(item.tasks,e)}</ul>`;
 const overviewAttention=attentionForCase(item).slice(0,6);
 const unresolvedEvents=(item.study_events||[]).filter(x=>!x.resolved_at).length;
 const pendingTasks=(item.tasks||[]).filter(x=>x.status==='pending').length;
 const currentFlowStage=phase==='baseline'?'baseline':phase==='intervention'?'intervention':phase==='maintenance'?'maintenance':['complete','withdrawn'].includes(phase)?'closeout':'setup';
 const studyFlow=[['setup','Setup'],['baseline','Baseline'],['intervention','Intervention'],['maintenance','Maintenance'],['closeout','Closeout']]
   .map(([key,label])=>`<span class="study-flow-step ${key===currentFlowStage?'current':''}">${e(label)}</span>`).join('');
 const overviewAttentionMarkup=overviewAttention.length
   ? `<ul class="overview-attention-list">${overviewAttention.map(reason=>`<li>${e(reason)}</li>`).join('')}</ul>`
   : '<p class="ready">Nothing needs attention right now.</p>';
 const thisWeekMarkup=phase==='intervention'
   ? `<div class="overview-metric"><span>Observations</span><strong>${stats.thisWeek}/3</strong></div><div class="overview-metric"><span>IOA coverage</span><strong>${pct(stats.ioa.percent||0)}</strong></div><div class="overview-metric"><span>Open tasks</span><strong>${pendingTasks}</strong></div><div class="overview-metric"><span>Unresolved events</span><strong>${unresolvedEvents}</strong></div>`
   : `<div class="overview-metric"><span>Current phase</span><strong>${e(phaseLabel)}</strong></div><div class="overview-metric"><span>Completed observations</span><strong>${stats.rows.length}</strong></div><div class="overview-metric"><span>Open tasks</span><strong>${pendingTasks}</strong></div><div class="overview-metric"><span>Unresolved events</span><strong>${unresolvedEvents}</strong></div>`;
 const completeChecklist=(key,allowNA=false)=>allowNA?['complete','not_applicable'].includes(checklist[key]?.status):checklist[key]?.status==='complete';
 const permissionReady=completeChecklist('teacher_consent')&&completeChecklist('parent_permission')&&completeChecklist('student_assent',true);
 const bspPrepKeys=['bsp_technical_review','safety_screen','target_routine_finalized','target_behavior_definition','fidelity_checklist_finalized','fidelity_checklist_second_review'];
 const bspPrepReady=bspPrepKeys.every(key=>completeChecklist(key));
 const tsesPreReady=measures.tses_pre?.status==='complete';
 const baselineAssignmentReady=Boolean(item.protocol);
 const baselineOrientationReady=completeChecklist('baseline_orientation');
 const observationSetupReady=(item.observation_data?.setups||[]).length>0;
 const observerReady=(item.observation_data?.observers||[]).some(x=>x.active&&x.status==='qualified');
 const baselineLaunchReady=baseline.ready&&observationSetupReady&&observerReady;
 const resourceReviewsReady=resourceReady&&prepared.resource_map?.behavior_reviewed===true&&prepared.resource_map?.privacy_reviewed===true;
 const qaPreviewReady=prepared.resource_map?.qa_previewed===true;
 const interventionOrientationReady=completeChecklist('intervention_orientation');
 const setupStatus=(ready,readyLabel='Complete',needsLabel='Needs action')=>`<span class="setup-readiness-status ${ready?'ready':'needs'}">${ready?readyLabel:needsLabel}</span>`;
 const setupRow=(label,ready,detail,target,help,readyLabel='Complete',needsLabel='Needs action')=>`<div class="setup-readiness-row"><div class="setup-readiness-copy"><strong>${e(label)}</strong><small>${e(detail)}</small><span class="setup-how"><b>How:</b> ${e(help)}</span></div>${setupStatus(ready,readyLabel,needsLabel)}<button type="button" class="quiet setup-detail-jump" data-setup-detail-target="${target}">View / Edit</button></div>`;
 const baselineLaunchRows=[
   setupRow('Permissions',permissionReady,'Teacher consent · Parent permission · Student assent','operations-enrollment','Obtain the required consent/permission/assent forms, then record each status and date here.'),
   setupRow('BSP + measurement',bspPrepReady,'Technical review · Safety · Routine · Behavior definition · Fidelity checklist','operations-enrollment','Review the existing BSP, complete the safety screen, finalize the observation routine and target-behavior definition, then finalize and second-review the fidelity checklist.'),
   setupRow('TSES Pre',tsesPreReady,'Pre-baseline teacher efficacy measure','operations-enrollment','Open the TSES Pre Qualtrics survey from this section, then record the measure as Complete after it is submitted.'),
   setupRow('Baseline assignment',baselineAssignmentReady,assignment,'operations-prebaseline','Choose stagger position 1–5 here. Research Admin converts that to the planned 6, 8, 10, 12, or 14-observation minimum.',baselineAssignmentReady?'Assigned':'Needs assignment','Needs assignment'),
   setupRow('Baseline orientation',baselineOrientationReady,'Study logistics and observation procedures','operations-prebaseline','Complete the logistics-only teacher orientation, including observation scheduling and study timeline, then mark it Complete.'),
   setupRow('Observation setup',observationSetupReady,'Routine and target behavior measurement setup','operations-prebaseline','Enter the selected routine and operational target-behavior definition here. The routine clock time is added when you build the weekly observation schedule.'),
   setupRow('Observer readiness',observerReady,'At least one observer cleared for live collection','operations-prebaseline','This updates automatically. Finish observer training/calibration in Observer Training and manually clear at least one observer for live data collection.',observerReady?'Observer available':'Needs cleared observer','Needs cleared observer')
 ].join('');
 const interventionPrepRows=[
   setupRow('Teacher account',teacherReady,'Secure teacher account ready for Mission: Reinforceable','participant-setup-details','Use Intake Information → Accounts → Create Teacher Account. Research Admin creates the Supabase Auth account for you; do not create it manually in Supabase.',teacherReady?'Ready':'Needs account','Needs account'),
   setupRow('Protected game content',contentPresent,'Published case-specific game content','operations-game-ready','Go to Game Creation, finish the case-specific content, run Full Draft Check, and publish the protected version. No GitHub editing is required.'),
   setupRow('Resource Map + reviews',resourceReviewsReady,'Resource Map · Behavior review · Privacy review','operations-game-ready','Complete the Resource Map in Game Creation, then record the Behavior Review and Privacy Review signoffs.'),
   setupRow('QA preview',qaPreviewReady,'Published game reviewed before launch','operations-game-ready','Preview the published protected game as the QA case, verify the teacher experience, then record the QA Preview signoff.'),
   setupRow('MR orientation',interventionOrientationReady,'Teacher orientation to Mission: Reinforceable','operations-game-ready','After the published game is ready, orient the teacher to accessing and using Mission: Reinforceable, then mark the orientation Complete.')
 ].join('');
 const setupNext=baselineLaunchReady
   ? (game.ready?'Baseline launch and intervention preparation are ready.':'Baseline launch is ready. Continue intervention preparation while baseline is running.')
   : `${baseline.remaining + (observationSetupReady?0:1) + (observerReady?0:1)} baseline launch item${baseline.remaining + (observationSetupReady?0:1) + (observerReady?0:1)===1?'':'s'} still need attention.`;
 const setupDashboard=`<section id="operations-setup-dashboard" class="panel operations-section operations-stage-panel setup-launch-dashboard" data-operations-stage-panel="setup" hidden>
   <div class="setup-launch-heading">
     <div><p class="eyebrow">Setup</p><h2>Launch Readiness</h2><p>Use this as the case setup checklist. Open a detail section only when something needs review or editing.</p><p class="setup-system-note"><strong>Normal case setup happens in Research Admin.</strong> You should not need to manually edit Supabase or GitHub for routine participant setup.</p></div>
     <span class="setup-launch-badge ${baselineLaunchReady?'ready':'needs'}">${baselineLaunchReady?'Baseline Ready':'Setup in Progress'}</span>
   </div>
   <p class="setup-next">${e(setupNext)}</p>
   <div class="setup-readiness-columns">
     <section class="setup-readiness-group"><div class="setup-group-heading"><div><h3>Baseline Launch</h3><p>Required before classroom baseline data collection begins.</p></div>${setupStatus(baselineLaunchReady,'READY','NOT READY')}</div><div class="setup-readiness-list">${baselineLaunchRows}</div></section>
     <section class="setup-readiness-group"><div class="setup-group-heading"><div><h3>Intervention Preparation</h3><p>Can be completed while baseline is running.</p></div>${setupStatus(game.ready,'READY','IN PROGRESS')}</div><div class="setup-readiness-list">${interventionPrepRows}</div><div class="intervention-launch-instructions"><strong>When Intervention actually starts:</strong><ol><li>Record the phase change to Intervention.</li><li>Open the Intervention tab and click <b>Activate Game Access</b>.</li><li>Click <b>Send Game Login</b> so the teacher receives password/setup instructions.</li><li>Click <b>Enable Daily Reminders</b>.</li></ol><small>Those buttons handle the underlying account/access/email systems. No manual Supabase or GitHub step is part of the normal launch workflow.</small></div></section>
   </div>
 </section>`;
 return `<nav class="operations-subnav" aria-label="Research Operations stages">${[['Overview','overview'],['Setup','setup'],['Baseline','baseline'],['Intervention','intervention'],['Maintenance','maintenance'],['Closeout','closeout'],['History','history']].map(([label,id])=>`<button type="button" class="operations-stage-tab" data-operations-stage="${id}" aria-selected="false">${label}</button>`).join('')}</nav>
${setupDashboard}
<div class="operations-stage-panel participant-setup-stage" data-operations-stage-panel="setup" hidden><!-- PARTICIPANT_READINESS --></div>
<section id="operations-overview" class="panel command-status operations-section operations-stage-panel" data-operations-stage-panel="overview"><div class="operations-overview-head"><div><p class="eyebrow">Case Overview</p><h2>${e(item.study_id)} · ${e(item.student_alias)}</h2></div><span class="phase-chip">${e(phaseLabel)}</span></div><div class="study-flow-bar" aria-label="Study flow">${studyFlow}</div><div class="overview-focus-grid"><section class="overview-focus-card attention-card"><h3>Needs Attention</h3>${overviewAttentionMarkup}</section><section class="overview-focus-card"><h3>This Week</h3><div class="overview-metrics">${thisWeekMarkup}</div></section><section class="overview-focus-card"><h3>Current Status</h3><dl class="overview-status-list"><div><dt>Latest fidelity</dt><dd>${pct(stats.latest?.teacher_fidelity_percent)}</dd></div><div><dt>Student target behavior</dt><dd>${pct(stats.latest?.student_target_behavior_percent)}</dd></div><div><dt>Game / reminders</dt><dd>${gameOn?'On':'Off'} / ${remindersOn?'On':'Off'}</dd></div><div><dt>Baseline assignment</dt><dd>${assignment}</dd></div></dl></section><aside class="overview-focus-card next-decision-card"><p class="eyebrow">Next Decision</p><strong>${e(nextAction(item))}</strong><small>Research Admin never changes phase automatically.</small></aside></div></section>
<section id="operations-phase-decision" class="panel operations-section operations-stage-panel phase-decision" data-operations-stage-panel="overview"><details class="phase-decision-disclosure"><summary>Review / Change Phase</summary><p class="neutral-note">Use this only when you are deliberately recording a research phase decision.</p><form id="phase-form" class="compact-form"><label>Selected phase<select name="phase">${opts(PHASES,phase)}</select></label><label>Effective date<input name="effective_date" type="date" required></label><label>Reason / decision note<textarea name="note" maxlength="1000"></textarea></label>${privacy}<button class="primary">Record Phase Change</button></form><h3>Phase History</h3><ol>${(item.phase_history||[]).map(x=>`<li>${e(x.effective_date)} · <strong>${e(x.phase)}</strong></li>`).join('')||'<li>No phase change recorded yet. Current phase: Prebaseline.</li>'}</ol></details></section>
<details id="operations-enrollment" class="panel operations-section operations-stage-panel setup-detail-panel" data-operations-stage-panel="setup" hidden><summary><span>Permissions, BSP &amp; Prebaseline Measure</span><small>Consent/permission, BSP review, fidelity measurement setup, and TSES Pre</small></summary><div class="setup-detail-body"><p class="eyebrow">Enrollment &amp; Preparation</p><h2>Permissions, BSP Review &amp; Measurement</h2><div class="baseline-checklist-grid formal-permissions">${formal}</div>${tsesRecording}<h3>Early Prep</h3><p class="neutral-note">Once teacher consent is in, you can begin BIP/BSP review and game prep while family permission and student assent are being completed. Research data collection still waits for required permissions.</p>${checklist.teacher_consent?.status==='complete'&&(checklist.parent_permission?.status!=='complete'||!['complete','not_applicable'].includes(checklist.student_assent?.status))?'<p class="needs">Game prep can begin. Research data collection is not ready yet.</p>':''}<div class="baseline-checklist-grid early-prep">${prep}</div>${privacy}</div></details>
<details id="operations-prebaseline" class="panel operations-section operations-stage-panel setup-detail-panel" data-operations-stage-panel="setup" hidden><summary><span>Baseline Logistics</span><small>Baseline assignment, orientation, routine/measurement setup, and observer readiness</small></summary><div class="setup-detail-body"><p class="eyebrow">Baseline Logistics</p><h2>Get Ready to Collect Baseline Data</h2>${protocolControl}<small class="privacy-help">Baseline assignment is locked once baseline begins.</small><h3>Baseline orientation</h3><div class="baseline-checklist-grid">${orientation}</div>${renderObservationSetup(item,e)}<div class="readiness-summary"><span>Observer readiness / qualification</span><strong>${(item.observation_data?.observers||[]).some(x=>x.active&&(x.observer_type==='primary_researcher'||x.status==='qualified'))?'Observer available':'Needs a qualified observer'}</strong><span>Observation setup</span><strong>${(item.observation_data?.setups||[]).length?'Ready':'Needs setup'}</strong></div><p class="${baseline.ready?'ready':'needs'}">${baseline.ready?'Ready to begin baseline.':`${baseline.remaining} readiness item${baseline.remaining===1?'':'s'} left.`}</p>${baselineLaunchReady?'<button class="quiet operations-stage-jump" type="button" data-operations-stage-target="overview">Review phase decision</button>':''}<p>Ready does not start baseline.</p></div></details>
<section id="operations-baseline" class="panel operations-section operations-stage-panel" data-operations-stage-panel="baseline" hidden>${renderPhaseObservationWorkspace(item,'baseline',e)}<details class="baseline-coaching"><summary>Coaching-as-Usual Contacts (${(item.coaching_contacts||[]).length})</summary><p class="neutral-note">Document school/district coaching that occurs outside Mission: Reinforceable so baseline conditions remain interpretable.</p>${coaching}</details></section>
<details id="operations-game-ready" class="panel operations-section game-ready-checkpoint operations-stage-panel setup-detail-panel" data-operations-stage-panel="setup" hidden><summary><span>Intervention Preparation</span><small>Teacher account, game content, Resource Map reviews, QA preview, and MR orientation</small></summary><div class="setup-detail-body"><p class="eyebrow">Intervention Preparation</p><h2>Prepare for Intervention</h2><p>Complete game preparation before intervention begins. Teacher access and daily reminders stay off until the intervention start.</p><p class="game-readiness-status ${game.ready?'ready':'needs'}">${launchHeadline}</p>${game.ready?'':`<p class="needs"><strong>${game.missing.length} item${game.missing.length===1?'':'s'} still need attention</strong></p>`}<div class="launch-status-list">${statusRow('Protected game content',contentPresent)}${statusRow('Resource Map',resourceReady)}${statusRow('Behavior Review',prepared.resource_map?.behavior_reviewed===true,'Complete','Needs review')}${statusRow('Privacy Review',prepared.resource_map?.privacy_reviewed===true,'Complete','Needs review')}${statusRow('QA Preview',prepared.resource_map?.qa_previewed===true,'Complete','Needs review')}${statusRow('Teacher account',teacherReady,'Ready','Needs account')}${statusRow('MR intervention orientation',checklist.intervention_orientation?.status==='complete','Complete','Pending')}</div><button id="open-game-creation" class="primary" type="button">Open Game Creation</button></div></details>
<section id="operations-intervention" class="panel operations-section ${phase==='intervention'?'active-stage':''} operations-stage-panel" data-operations-stage-panel="intervention" hidden><p class="eyebrow">Intervention</p>${phase==='intervention'?interventionFull:`<div class="future-stage-preview"><h2>${['prebaseline','baseline'].includes(phase)?'Not started.':'Intervention complete.'}</h2><p>Game access: <strong>${gameOn?'On':'Off'}</strong><br>Reminders: <strong>${remindersOn?'On':'Off'}</strong></p>${['prebaseline','baseline'].includes(phase)?'<p>Mission: Reinforceable intervention tools become active when Intervention begins.</p>':''}<details><summary>View Intervention Details</summary>${interventionFull}</details></div>`}</section>
${studyDayContext}
<section id="operations-maintenance" class="panel operations-section operations-stage-panel" data-operations-stage-panel="maintenance" hidden><p class="eyebrow">Maintenance</p>${['maintenance','complete'].includes(phase)?maintenanceFull:`<div class="future-stage-preview"><h2>Begins after Mission: Reinforceable is withdrawn.</h2><p>Target: 2–3 observations across approximately 3–5 weeks.</p><details><summary>View Maintenance Details</summary>${maintenanceFull}</details></div>`}</section>
<section id="operations-end-measures" class="panel operations-section operations-stage-panel" data-operations-stage-panel="closeout" hidden><p class="eyebrow">End Measures</p>${phase==='complete'?endMeasuresFull:`<div class="future-stage-preview"><h2>Available after maintenance is deliberately ended.</h2><p>TSES — Post-Intervention<br>URP-IR — Post-Intervention<br>Teacher Interview — Post-Intervention</p></div>`}</section>
<section id="operations-closeout" class="panel operations-section operations-stage-panel" data-operations-stage-panel="closeout" hidden><p class="eyebrow">Closeout</p>${phase==='complete'?closeoutFull:`<div class="future-stage-preview"><h2>Available after maintenance and End Measures.</h2><details><summary>View Closeout Details</summary>${closeoutFull}</details></div>`}</section>
<section id="operations-events" class="panel operations-section operations-stage-panel" data-operations-stage-panel="history" hidden><p class="eyebrow">Study Events</p><h2>Events that affected the study</h2><p>Absences, schedule changes, tech issues, BIP/BSP changes, safety concerns, and anything else that affected the study.</p><form id="event-form" class="compact-form"><label>Date<input name="date" type="date" required></label><label>Type<select name="type">${opts(['teacher_absence','student_absence','school_schedule_disruption','missed_observation','technical_issue','email_delivery_issue','bsp_change','safety_concern','support_requested','withdrawal','placement_change','protocol_deviation','observer_issue','advisor_pi_decision','other'])}</select></label><label class="check-option"><input type="checkbox" name="affects_observation"> Affected an observation</label><label class="check-option"><input type="checkbox" name="affects_mr_exposure"> Affected MR access/practice</label><label class="check-option"><input type="checkbox" name="affects_phase_interpretation"> Could affect interpretation</label><label>What happened?<textarea name="note" maxlength="1000" required></textarea></label><label>What did you do? — optional<textarea name="action_taken" maxlength="1000"></textarea></label>${privacy}<button class="primary">Save Event</button></form><ul>${eventRows}</ul></section>
<section id="operations-history" class="panel operations-section operations-stage-panel" data-operations-stage-panel="history" hidden><p class="eyebrow">Case History</p><h2>What already happened</h2><p>The lifecycle view tells you what to do now. This append-only history shows what already happened.</p><ol class="timeline">${timeline.map(x=>`<li><time>${e(String(x.date).slice(0,10))}</time><strong>${e(x.category)}</strong><span>${e(x.label)}</span></li>`).join('')||'<li>No events recorded.</li>'}</ol></section>`;
}
