import { CHECKLIST, MEASURES, PHASES, COACHING_FOCUSES, TASK_CATEGORIES, currentByKey, baselineReadiness, attentionForCase, timelineForCase, denverToday, checklistStatuses } from './operations-model.mjs';
export const privacy='<small class="privacy-help">Keep notes brief and operational. Do not include student names, diagnoses, or protected BSP content.</small>';
const opts=(values,current)=>values.map(v=>`<option value="${v}" ${v===current?'selected':''}>${v.replaceAll('_',' ')}</option>`).join('');
export function taskList(tasks,e){return (tasks||[]).map(t=>`<li class="${t.overdue?'high-attention':''}"><strong>${e(t.title)}</strong> · ${e(t.status)}${t.required?' · Required':''}${t.due_date?` · due ${e(t.due_date)}`:''}${t.note?`<br><span>${e(t.note)}</span>`:''}<span class="row-actions">${t.status==='pending'?`<button class="quiet task-action" data-id="${t.id}" data-status="complete">Complete</button><button class="quiet task-action" data-id="${t.id}" data-status="not_applicable">Mark N/A</button>`:`<button class="quiet task-action" data-id="${t.id}" data-status="pending">Reopen</button>`}</span></li>`).join('')||'<li>No tasks recorded.</li>';}
export function taskForm(id,heading='Add task'){return `<form id="${id}" class="compact-form"><h3>${heading}</h3><label>Title<input name="title" maxlength="160" required></label><label>Category<select name="category">${opts(TASK_CATEGORIES)}</select></label><label>Due date — optional<input name="due_date" type="date"></label><label class="check-option"><input name="required" type="checkbox"> Required?</label><label>Optional note<textarea name="note" maxlength="1000"></textarea></label>${privacy}<button class="primary">Add task</button></form>`;}
export function renderStudyWideTasks(tasks,e){return `<section class="panel study-wide-tasks"><p class="eyebrow">Study-Wide Tasks</p><h2>Dissertation operations</h2>${taskForm('study-task-form','Add study-wide task')}<ul>${taskList(tasks,e)}</ul></section>`;}
export function renderOperations(item,prepared,e,allCases=[]){
 if(!item)return '';
 const checklist=currentByKey(item.checklist),measures=currentByKey(item.measures,'measure_key'),baseline=baselineReadiness(item),attention=attentionForCase(item),timeline=timelineForCase(item);
 const checklistRows=CHECKLIST.map(([key,label])=>{const row=checklist[key]||{},statuses=checklistStatuses(key);return `<form class="inline-record checklist-form" data-key="${key}"><strong>${e(label)}</strong><select name="status">${opts(statuses,row.status||'pending')}</select><input name="status_date" type="date" required value="${e(row.status_date||denverToday())}" aria-label="Status date for ${e(label)}"><input name="note" maxlength="1000" value="${e(row.brief_note||'')}" aria-label="Optional note for ${e(label)}" placeholder="Optional brief note"><button class="quiet">Save</button></form>`}).join('');
 const measureRows=MEASURES.map(([key,label])=>{const row=measures[key]||{};return `<form class="inline-record measure-form" data-key="${key}"><strong>${e(label)}</strong><select name="status">${opts(['pending','complete','declined','not_applicable'],row.status||'pending')}</select><input name="completed_on" type="date" value="${e(row.completed_on||'')}" aria-label="Completion date"><input name="external_reference" maxlength="250" value="${e(row.external_reference||'')}" placeholder="Optional external reference"><input name="note" maxlength="1000" value="${e(row.brief_note||'')}" placeholder="Optional brief note"><button class="quiet">Save</button></form>`}).join('');
 const events=(item.study_events||[]).map(x=>`<li class="${['safety_concern','protocol_deviation'].includes(x.event_type)&&!x.resolved_at?'high-attention':''}"><strong>${e(x.event_type.replaceAll('_',' '))}</strong> · ${e(x.event_date)} · ${x.resolved_at?'Resolved':`Unresolved <button class="quiet resolve-event" data-id="${x.id}">Resolve / update action</button>`}${x.action_taken?`<br>Action: ${e(x.action_taken)}`:''}</li>`).join('')||'<li>No study events.</li>';
 return `<section class="panel command-status"><p class="eyebrow">Case Status / Needs Attention</p><h2>${e(item.study_id)} · ${e(item.student_alias)}</h2><p><strong>Case ID:</strong> ${e(item.case_code)} · <strong>Phase:</strong> ${e(item.current_phase)} · <strong>Planned minimum:</strong> ${item.protocol?.planned_baseline_observations||'Not assigned'}<br><strong>Game access:</strong> ${item.case_active&&item.participant_active?'ON':'OFF intentionally'} · <strong>Reminders:</strong> ${prepared.reminders?.enabled?'ON':'OFF intentionally'}</p>${attention.length?`<div class="attention"><h3>Needs Attention</h3><ul>${attention.map(x=>`<li>${e(x)}</li>`).join('')}</ul></div>`:'<p class="ready">No current actionable needs</p>'}</section>
<section class="panel"><p class="eyebrow">Protocol Setup</p><h2>Baseline Readiness</h2><form id="protocol-form" class="compact-form"><label>Stagger position (1–5)<input name="position" type="number" min="1" max="5" value="${item.protocol?.stagger_position||''}" required></label><button class="primary">Save deliberate assignment</button></form>${item.protocol?`<form id="protocol-swap-form" class="compact-form"><h3>Swap assigned positions</h3><label>Swap with another prebaseline case<select name="other_case_id" required><option value="">Select case</option>${allCases.filter(x=>x.id!==item.id&&x.protocol).map(x=>`<option value="${x.id}">${e(x.study_id)} · position ${x.protocol.stagger_position}</option>`).join('')}</select></label><button class="quiet">Swap positions atomically</button></form>`:''}<p class="${baseline.ready?'ready':'needs'}">${baseline.ready?'READY TO BEGIN BASELINE':`${baseline.remaining} requirements remaining`}</p><div class="inline-record-list">${checklistRows}</div><p><strong>The researcher must explicitly record baseline.</strong> Readiness never starts it automatically.</p>${privacy}</section>
<section class="panel"><p class="eyebrow">Phase History</p><h2>Current: ${e(item.current_phase)}</h2><p class="neutral-note"><strong>Study phase is separate from Mission: Reinforceable access.</strong></p><form id="phase-form" class="compact-form"><label>Phase<select name="phase">${opts(PHASES,item.current_phase)}</select></label><label>Effective date<input name="effective_date" type="date" required></label><label>Decision note<textarea name="note" maxlength="1000"></textarea></label>${privacy}<button class="primary">Record explicit phase decision</button></form><ol>${(item.phase_history||[]).map(x=>`<li>${e(x.effective_date)} · <strong>${e(x.phase)}</strong></li>`).join('')||'<li>No event: operational default is prebaseline.</li>'}</ol></section>
<section class="panel"><p class="eyebrow">Measures</p><h2>Administration / completion only</h2><p>Actual questionnaire responses and interview content remain in the approved data system. Completion date is required only for Complete.</p><div class="inline-record-list">${measureRows}</div>${privacy}</section>
<section class="panel"><p class="eyebrow">Research Tasks</p><h2>Operational ledger</h2>${taskForm('task-form','Add case task')}<ul>${taskList(item.tasks,e)}</ul></section>
<section class="panel"><p class="eyebrow">Coaching-as-Usual</p><h2>School/district support context</h2><p><strong>Documented for context; not directed by the researcher.</strong></p><form id="coaching-form" class="compact-form"><label>Date<input name="date" type="date" required></label><label>Format<select name="format">${opts(['in_person','virtual','email','phone','other'])}</select></label><label>Approximate duration in minutes — optional<input name="duration" type="number" min="1" max="1440"></label><label>Provider role<input name="provider" maxlength="160" required></label><fieldset><legend>General focus — select at least one</legend><div class="choice-grid">${COACHING_FOCUSES.map(x=>`<label class="check-option"><input type="checkbox" name="focus" value="${x}"> ${x.replaceAll('_',' ')}</label>`).join('')}</div></fieldset><label>Brief operational note — optional<textarea name="note" maxlength="1000"></textarea></label>${privacy}<button class="primary">Add coaching contact</button></form><ol>${(item.coaching_contacts||[]).map(x=>`<li>${e(x.contact_date)} · ${e(x.format)} · ${e(x.provider_role)}${x.approximate_duration_minutes?` · ~${x.approximate_duration_minutes} minutes`:''} · ${e(x.focuses.join(', '))}</li>`).join('')||'<li>No contacts recorded.</li>'}</ol></section>
<section class="panel"><p class="eyebrow">Study Events / Deviations</p><h2>Context and disruptions</h2><form id="event-form" class="compact-form"><label>Date<input name="date" type="date" required></label><label>Type<select name="type">${opts(['teacher_absence','student_absence','school_schedule_disruption','missed_observation','technical_issue','email_delivery_issue','bsp_change','safety_concern','support_requested','withdrawal','placement_change','protocol_deviation','observer_issue','advisor_pi_decision','other'])}</select></label><label class="check-option"><input type="checkbox" name="affects_observation"> Did this affect a planned classroom observation?</label><label class="check-option"><input type="checkbox" name="affects_mr_exposure"> Did this affect expected Mission: Reinforceable exposure?</label><label class="check-option"><input type="checkbox" name="affects_phase_interpretation"> Could this affect interpretation of the study phase/data?</label><label>Brief operational note<textarea name="note" maxlength="1000" required></textarea></label><label>Action taken — optional<textarea name="action_taken" maxlength="1000"></textarea></label>${privacy}<button class="primary">Add study event</button></form><ul>${events}</ul></section>
<section class="panel"><p class="eyebrow">Intervention Preparation</p><h2>Context — no automatic activation</h2><div class="checklist"><div><span>Protected content</span><strong>${prepared.protected_content?.present?'Present':'Needs action'}</strong></div><div><span>Resource Map</span><strong>${e(prepared.resource_map?.status||'Needs action')}</strong></div><div><span>Mission Bank Comparability</span><strong>${e(prepared.mission_bank_comparability?.status||'Needs action')}</strong></div><div><span>Intervention orientation</span><strong>${e(checklist.intervention_orientation?.status||'pending')}</strong></div><div><span>Game / reminders</span><strong>${item.case_active&&item.participant_active?'ON':'OFF intentionally'} / ${prepared.reminders?.enabled?'ON':'OFF intentionally'}</strong></div></div></section>
<section class="panel"><p class="eyebrow">Case Timeline</p><h2>Chronological operations history</h2><ol class="timeline">${timeline.map(x=>`<li><time>${e(String(x.date).slice(0,10))}</time><strong>${e(x.category)}</strong><span>${e(x.label)}</span></li>`).join('')||'<li>No operations events recorded.</li>'}</ol></section>`;
}
