import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),handler=require('./research-admin-set-teacher-reminders');
const uuid='11111111-1111-4111-8111-111111111111';
function response(){return{statusCode:0,body:null,setHeader(){},status(value){this.statusCode=value;return this;},json(value){this.body=value;return value;}};}
function fetchStub(calls){return async(url,options={})=>{calls.push({url:String(url),options});if(String(url).includes('/auth/v1/user'))return{ok:true,json:async()=>({id:uuid})};if(String(url).includes('/profiles?'))return{ok:true,json:async()=>[{id:uuid,role:'research_admin',active:true}]};return{ok:true,status:200,json:async()=>({enabled:JSON.parse(options.body).target_enabled,changed_at:'now'})};};}
test('one env kill switch blocks enable before the database path',async()=>{const calls=[];global.fetch=fetchStub(calls);process.env.SUPABASE_URL='https://example.test';process.env.SUPABASE_SERVICE_ROLE_KEY='secret';delete process.env.TEACHER_REMINDER_SYSTEM_ENABLED;const res=response();await handler({method:'POST',headers:{authorization:'Bearer user'},body:{case_id:uuid,enabled:true}},res);assert.equal(res.statusCode,503);assert.equal(res.body.error,'Production email delivery has not been enabled.');assert.ok(!calls.some(x=>x.url.includes('/rpc/')));});
test('true flag permits enable to the internal RPC',async()=>{const calls=[];global.fetch=fetchStub(calls);process.env.TEACHER_REMINDER_SYSTEM_ENABLED='true';const res=response();await handler({method:'POST',headers:{authorization:'Bearer user'},body:{case_id:uuid,enabled:true}},res);assert.equal(res.statusCode,200);assert.equal(calls.filter(x=>x.url.includes('/rpc/research_admin_set_teacher_reminders')).length,1);});
test('false flag never prevents reminder shutdown',async()=>{const calls=[];global.fetch=fetchStub(calls);process.env.TEACHER_REMINDER_SYSTEM_ENABLED='false';const res=response();await handler({method:'POST',headers:{authorization:'Bearer user'},body:{case_id:uuid,enabled:false}},res);assert.equal(res.statusCode,200);assert.equal(calls.filter(x=>x.url.includes('/rpc/research_admin_set_teacher_reminders')).length,1);delete process.env.TEACHER_REMINDER_SYSTEM_ENABLED;delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;});
